site_name: OpenStack Data Plane Adoption
site_description: OpenStack Data Plane Adoption
site_author: OpenStack Team
site_url: https://openstack-k8s-operators.github.io/data-plane-adoption
repo_name: openstack-k8s-operators/data-plane-adoption
repo_url: https://github.com/openstack-k8s-operators/data-plane-adoption
theme:
  features:
    - search.suggest
    - search.highlight
    - search.share
  name: material
  logo: images/openstack-logo.png
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
nav:
  - Overview: README.md
  - OpenStack:
    - openstack/backend_services_deployment.md
    - openstack/stop_openstack_services.md
    - openstack/mariadb_copy.md
    - openstack/ovn_adoption.md
    - openstack/keystone_adoption.md
    - openstack/neutron_adoption.md
    - openstack/ceph_backend_configuration.md
    - openstack/glance_adoption.md
    - openstack/placement_adoption.md
    - openstack/cinder_adoption.md
    - openstack/horizon_adoption.md
    - openstack/edpm_adoption.md
    - openstack/troubleshooting.md
  - Ceph:
    - Ceph RBD migration: ceph/ceph_rbd.md
    - Ceph RGW migration: ceph/ceph_rgw.md
  - Contributing:
    - contributing/documentation.md
    - contributing/development_environment.md
    - contributing/tests.md
markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.superfences
  - admonition
extra:
  version:
    provider: mike
    default: latest
plugins:
  - git-revision-date
  - search:
      lang: en
      prebuild_index: true
