:_mod-docs-content-type: CONCEPT
[id="post-adoption-tasks_{context}"]

= Post-adoption tasks

[role="_abstract"]
Perform the following post-adoption tasks to ensure that your {rhos_long} environment is functioning optimally.

* After adoption, {rhos_acro} data plane nodes run Red Hat Enterprise Linux (RHEL) 9.2. The data plane nodes can remain on RHEL 9.2; however, you must perform a system update to use the full feature set from the release, and to align your environment with the maximum support lifecycle of {rhos_acro}.
** You can perform a system update any time after you complete the adoption procedure.
** You can defer the system update to a separate maintenance window.
** You can perform the system update on one node set at a time. For example, you can update one node set from RHEL 9.2 to RHEL 9.4 or 9.6 in one maintenance window, and then update a different node set in another maintenance window later.
* If you enabled the high availability for Compute instances (Instance HA) service, remove the Pacemaker components from your Compute nodes.
* Enable TLS Everywhere (TLS-e).
* Verify that you migrated all services from the Controller nodes, and then power off the nodes. If any services are still running in the Controller nodes, such as Open Virtual Networking (ML2/OVN), {object_storage_first_ref}, or {Ceph}, do not power off the nodes.
* Optional: Run tempest to verify that the entire adoption process is working correctly.

.Additional resources

* link:https://docs.redhat.com/en/documentation/red_hat_openstack_services_on_openshift/18.0/html/updating_your_environment_to_the_latest_maintenance_release/index[Updating your environment to the latest maintenance release]
* xref:enabling-high-availability-for-instances_data-plane[Enabling the high availability for Compute instances service]
* link:https://docs.redhat.com/en/documentation/red_hat_openstack_services_on_openshift/18.0/html-single/configuring_security_services/index#assembly_enabling-TLS-on-a-deployed-RHOSO-environment[Enabling TLS on a deployed RHOSO environment] in _Configuring security services_
* link:https://docs.redhat.com/en/documentation/red_hat_openstack_services_on_openshift/18.0/html/validating_and_troubleshooting_the_deployed_cloud/index[Validating and troubleshooting the deployed cloud]
