[id="adopting-the-identity-service_{context}"]

//:context: adopting-identity-service

//kgilliga: This module might be converted to an assembly, or a procedure as a standalone chapter. Check xref context.

= Adopting the Identity service

== Prerequisites

* Previous Adoption steps completed. Notably,
 ** the xref:migrating-databases-to-mariadb-instances_{context}[Migrating databases to MariaDB instances]
must already be imported into the podified MariaDB.

== Variables

There are no shell variables necessary currently.

== Pre-checks

== Copy over fernet keys

* Create the `keystone` secret, containing fernet keys:
+
----
oc apply -f - <<EOF
apiVersion: v1
data:
  CredentialKeys0: $($CONTROLLER1_SSH sudo cat /var/lib/config-data/puppet-generated/keystone/etc/keystone/credential-keys/0 | base64 -w 0)
  CredentialKeys1: $($CONTROLLER1_SSH sudo cat /var/lib/config-data/puppet-generated/keystone/etc/keystone/credential-keys/1 | base64 -w 0)
  FernetKeys0: $($CONTROLLER1_SSH sudo cat /var/lib/config-data/puppet-generated/keystone/etc/keystone/fernet-keys/0 | base64 -w 0)
  FernetKeys1: $($CONTROLLER1_SSH sudo cat /var/lib/config-data/puppet-generated/keystone/etc/keystone/fernet-keys/1 | base64 -w 0)
kind: Secret
metadata:
  name: keystone
  namespace: openstack
type: Opaque
EOF
----


== Procedure - Keystone adoption

* Patch OpenStackControlPlane to deploy Keystone:
+
----
oc patch openstackcontrolplane openstack --type=merge --patch '
spec:
  keystone:
    enabled: true
    apiOverride:
      route: {}
    template:
      override:
        service:
          internal:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/allow-shared-ip: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.80
            spec:
              type: LoadBalancer
      databaseInstance: openstack
      secret: osp-secret
'
----

* Create alias to use `openstack` command in the adopted deployment:
+
----
alias openstack="oc exec -t openstackclient -- openstack"
----

* Clean up old services and endpoints that still point to the old
control plane (everything except Keystone service and endpoints):
+
----
openstack endpoint list | grep keystone | awk '/admin/{ print $2; }' | xargs ${BASH_ALIASES[openstack]} endpoint delete || true

for service in aodh heat heat-cfn barbican cinderv3 glance manila manilav2 neutron nova placement swift; do
  openstack service list | awk "/ $service /{ print \$2; }" | xargs ${BASH_ALIASES[openstack]} service delete || true
done
----

== Post-checks

* See that Keystone endpoints are defined and pointing to the podified
FQDNs:
+
----
openstack endpoint list | grep keystone
----
