[id="tls-everywhere_{context}"]

//:context: tls

//kgilliga: This module will be converted to an assembly. Check xref contexts.

= TLS Everywhere

_Disclaimer: the below steps were reproduced on a FreeIPA 4.10.1 server. The location of files and directories may slightly change on different versions._

== Prerequisites

* Check that the source deployment is using TLS Everywhere, skip this step if it's not.
* Make sure the previous Adoption steps have been performed successfully.
* Make sure the backend services on the new deployment are not started yet.

== Variables

Define the shell variables used in the following steps. The values are illustrative and refer to a single node standalone director deployment. Use values that are correct for your environment:

IPA_SSH="ssh -i ~/install_yamls/out/edpm/ansibleee-ssh-key-id_rsa root@192.168.122.100 podman exec -ti freeipa-server-container"

In this example the FreeIPA instance is running on a separate host, in a container.

== Transfer the CA certificate and key from FreeIPA to the cert-manager Operator

=== Exporting from FreeIPA

There are a couple of ways to do it:
1. You can copy the certificate from the `/etc/pki/pki-tomcat/alias` directory. The file is named `ca.crt`.
2. You can interact with the database located in the `/etc/pki/pki-tomcat/alias` directory ("*db" files).

==== Locating the CA certificate and key


List all the certificates inside your NSSDB:

----
$ $IPA_SSH certutil -L -d /etc/pki/pki-tomcat/alias
----

The `-L` option lists all certificates, and `-d` specifies where they are stored. This will produce some output like this:

----
Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

caSigningCert cert-pki-ca                                    CTu,Cu,Cu
ocspSigningCert cert-pki-ca                                  u,u,u
Server-Cert cert-pki-ca                                      u,u,u
subsystemCert cert-pki-ca                                    u,u,u
auditSigningCert cert-pki-ca                                 u,u,Pu
----

The item you need to consider is the first one: `caSigningCert cert-pki-ca`.

==== Exporting the items (certificate and key)

The command below generates a P12 file with both, the certificate and the key. The `/etc/pki/pki-tomcat/alias/pwdfile.txt` file contains the password that protects the key. You can use it to both, extract the key and generate the new file, `/tmp/freeipa.p12`. You can also choose another password. Should you choose to apply a different password for the new file, simply replace the parameter of the `-w` option, or alternatively use the `-W` (capital W) option followed by the password (in clear text).

----
$IPA_SSH pk12util -o /tmp/freeipa.p12 -n 'caSigningCert\ cert-pki-ca' -d /etc/pki/pki-tomcat/alias -k /etc/pki/pki-tomcat/alias/pwdfile.txt -w /etc/pki/pki-tomcat/alias/pwdfile.txt
----

With that file on hand, we can separately get the certificate and the key, using the openssl pkcs12 command.

The key length is another important property. You will need it below, when crafting one of the YAML files that will be used to provision the new custom resources. You can get it with:

----
$IPA_SSH openssl pkcs12 -in /tmp/freeipa.p12 -passin file:/etc/pki/pki-tomcat/alias/pwdfile.txt -nocerts -noenc | openssl rsa -text -noout | awk -F'[^0-9]+' '{ print $2; exit }'
----

==== Importing the Items and Provisioning the Custom Resources (CRs) on OpenShift

You will have to create two YAML files. The first one has three sections:

* The `openstack` namespace, which is used by other Red Hat OpenStack operators and CRs.
* The issuer. The cert-manager operator makes use of a self-signed issuer to issue both, the CA certificate itself and other certificates.
* The CA certificate itself. We are specifically naming it as `rootca-internal`, which corresponds to the certificate authority leveraged by cert-manager to issue other certificates.

Let's apply the following YAML file to create the corresponding CRs:

+
[source,yaml]
----
oc apply -f - <<EOF
apiVersion: v1
kind: Namespace
metadata:
  name: openstack
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: openstack
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rootca-internal
  namespace: openstack
spec:
  isCA: true
  commonName: rootca-internal
  secretName: rootca-internal
  privateKey:
    algorithm: RSA
    size: 3072
  issuerRef:
    name: selfsigned-issuer
EOF
----


OK, you just created the CRs with the initial content. Now you will need to import the certificate and the key that you exported from FreeIPA. You can do this with the `oc patch` command. For the CA certificate (correspondeing to the `ca.crt` item on the Certificate, type:

----
oc patch secret rootca-internal -n openstack -p="{\"data\":{\"ca.crt\": \"`$IPA_SSH openssl pkcs12 -in /tmp/freeipa.p12 -passin file:/etc/pki/pki-tomcat/alias/pwdfile.txt -nokeys | openssl x509 | base64 -w 0`\"}}"
----

You will also need to update the `tls.crt` item. For the CA, this will receive the very same contents of `ca.crt`. The command just needs a small adjustment:

----
oc patch secret rootca-internal -n openstack -p="{\"data\":{\"tls.crt\": \"`$IPA_SSH openssl pkcs12 -in /tmp/freeipa.p12 -passin file:/etc/pki/pki-tomcat/alias/pwdfile.txt -nokeys | openssl x509 | base64 -w 0`\"}}"
----

Finally, update the key:

----
oc patch secret rootca-internal -n openstack -p="{\"data\":{\"tls.key\": \"`$IPA_SSH openssl pkcs12 -in /tmp/freeipa.p12 -passin file:/etc/pki/pki-tomcat/alias/pwdfile.txt -nocerts -noenc | openssl rsa | base64 -w 0`\"}}"
----

Now create the cert-manager Issuer, referencing the created secret:

+
[source, yaml]
----
oc apply -f - <<EOF
apiVersion: v1
kind: Namespace
metadata:
  name: openstack
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: rootca-internal
  namespace: openstack
spec:
  ca:
    secretName: rootca-internal
EOF
----

==== Checking the newly provisioned CRs

You can check the created resources with the commands below:

----
oc get issuers -n openstack
----

----
oc get secret rootca-internal -n openstack -o yaml
----
