[id="migrating-databases-to-mariadb-instances_{context}"]

//kgilliga: This module will be converted to a procedure. Unclear which assembly it should be included in.
//Check xref contexts.

= Migrating databases to MariaDB instances

This document describes how to move the databases from the original
OpenStack deployment to the MariaDB instances in the OpenShift
cluster.

____
*NOTE* This example scenario describes a simple single-cell setup. Real
multi-stack topology recommended for production use results in different
cells DBs layout, and should be using different naming schemes (not covered
here this time).
____

== Prerequisites

* Make sure the previous Adoption steps have been performed successfully.
 ** The OpenStackControlPlane resource must be already created at this point.
 ** Podified MariaDB and RabbitMQ are running. No other podified
control plane services are running.
 ** Required services specific topology. For more information, see xref:pulling-the-openstack-configuration_{context}[Pulling the OpenStack configuration].
//kgilliga: this xref should specifically point to the Get services topology specific configuration module when it's ready.
 ** OpenStack services have been stopped. For more information, see xref:stopping-openstack-services_{context}[Stopping OpenStack services].
 ** There must be network routability between:
  *** The adoption host and the original MariaDB.
  *** The adoption host and the podified MariaDB.
  *** _Note that this routability requirement might change in the
future. For example, you might require routability from the original MariaDB to
podified MariaDB_.
* Podman package is installed
* `CONTROLLER1_SSH`, `CONTROLLER2_SSH`, and `CONTROLLER3_SSH` are configured.

== Variables

Define the shell variables used in the steps below. The values are
just illustrative, use values that are correct for your environment:

----
PODIFIED_MARIADB_IP=$(oc get svc --selector "mariadb/name=openstack" -ojsonpath='{.items[0].spec.clusterIP}')
PODIFIED_CELL1_MARIADB_IP=$(oc get svc --selector "mariadb/name=openstack-cell1" -ojsonpath='{.items[0].spec.clusterIP}')
PODIFIED_DB_ROOT_PASSWORD=$(oc get -o json secret/osp-secret | jq -r .data.DbRootPassword | base64 -d)

# The CHARACTER_SET and collation should match the source DB
# if the do not then it will break foreign key relationships
# for any tables that are created in the future as part of db sync
CHARACTER_SET=utf8
COLLATION=utf8_general_ci

MARIADB_IMAGE=quay.io/podified-antelope-centos9/openstack-mariadb:current-podified
# Replace with your environment's MariaDB IP:
SOURCE_MARIADB_IP=192.168.122.100
SOURCE_DB_ROOT_PASSWORD=$(cat ~/tripleo-standalone-passwords.yaml | grep ' MysqlRootPassword:' | awk -F ': ' '{ print $2; }')
----

== Pre-checks

* Get the count of not-OK source databases:
+
----
podman run -i --rm --userns=keep-id -u $UID $MARIADB_IMAGE \
    mysql -h "$SOURCE_MARIADB_IP" -uroot "-p$SOURCE_DB_ROOT_PASSWORD" -e 'SHOW databases;'
----

* Run mysqlcheck on the original DB to look for things that are not OK:
+
----
. ~/.source_cloud_exported_variables
test -z "$PULL_OPENSTACK_CONFIGURATION_MYSQLCHECK_NOK"  || [ "$PULL_OPENSTACK_CONFIGURATION_MYSQLCHECK_NOK" = " " ]
----

* Test connection to podified DBs (show databases):
+
----
oc run mariadb-client --image $MARIADB_IMAGE -i --rm --restart=Never -- \
    mysql -rsh "$PODIFIED_MARIADB_IP" -uroot "-p$PODIFIED_DB_ROOT_PASSWORD" -e 'SHOW databases;'
oc run mariadb-client --image $MARIADB_IMAGE -i --rm --restart=Never -- \
    mysql -rsh "$PODIFIED_CELL1_MARIADB_IP" -uroot "-p$PODIFIED_DB_ROOT_PASSWORD" -e 'SHOW databases;'
----

== Procedure - data copy

____
*NOTE*: You need to transition Nova services imported later on into a
superconductor architecture. For that, delete the old service records in
cells DBs, starting from the cell1. New records will be registered with
different hostnames provided by the Nova service operator. All Nova
services, except the compute agent, have no internal state, and its service
records can be safely deleted. You also need to rename the former `default` cell
to `cell1`.
____

* Create a temporary folder to store DB dumps and make sure it's the
working directory for the following steps:
+
----
mkdir ~/adoption-db
cd ~/adoption-db
----

* Create a dump of the original databases:
+
----
podman run -i --rm --userns=keep-id -u $UID -v $PWD:$PWD:z,rw -w $PWD $MARIADB_IMAGE bash <<EOF

# Note Filter the information and performance schema tables
# Gnocchi is no longer used as a metric store, skip dumping gnocchi database as well
mysql -h ${SOURCE_MARIADB_IP} -u root "-p${SOURCE_DB_ROOT_PASSWORD}" -N -e 'show databases' | grep -E -v 'schema|mysql|gnocchi' | while read dbname; do
    echo "Dumping \${dbname}"
    mysqldump -h $SOURCE_MARIADB_IP -uroot "-p$SOURCE_DB_ROOT_PASSWORD" \
        --single-transaction --complete-insert --skip-lock-tables --lock-tables=0 \
        "\${dbname}" > "\${dbname}".sql
done

EOF
----

* Restore the databases from .sql files into the podified MariaDB:
+
----
# db schemas to rename on import
declare -A db_name_map
db_name_map["nova"]="nova_cell1"
db_name_map["ovs_neutron"]="neutron"

# db servers to import into
declare -A db_server_map
db_server_map["default"]=${PODIFIED_MARIADB_IP}
db_server_map["nova_cell1"]=${PODIFIED_CELL1_MARIADB_IP}

# db server root password map
declare -A db_server_password_map
db_server_password_map["default"]=${PODIFIED_DB_ROOT_PASSWORD}
db_server_password_map["nova_cell1"]=${PODIFIED_DB_ROOT_PASSWORD}

all_db_files=$(ls *.sql)
for db_file in ${all_db_files}; do
    db_name=$(echo ${db_file} | awk -F'.' '{ print $1; }')
    if [[ -v "db_name_map[${db_name}]" ]]; then
        echo "renaming ${db_name} to ${db_name_map[${db_name}]}"
        db_name=${db_name_map[${db_name}]}
    fi
    db_server=${db_server_map["default"]}
    if [[ -v "db_server_map[${db_name}]" ]]; then
        db_server=${db_server_map[${db_name}]}
    fi
    db_password=${db_server_password_map["default"]}
    if [[ -v "db_server_password_map[${db_name}]" ]]; then
        db_password=${db_server_password_map[${db_name}]}
    fi
    echo "creating ${db_name} in ${db_server}"
    container_name=$(echo "mariadb-client-${db_name}-create" | sed 's/_/-/g')
    oc run ${container_name} --image ${MARIADB_IMAGE} -i --rm --restart=Never -- \
        mysql -h "${db_server}" -uroot "-p${db_password}" << EOF
CREATE DATABASE IF NOT EXISTS ${db_name} DEFAULT CHARACTER SET ${CHARACTER_SET} DEFAULT COLLATE ${COLLATION};
EOF
    echo "importing ${db_name} into ${db_server}"
    container_name=$(echo "mariadb-client-${db_name}-restore" | sed 's/_/-/g')
    oc run ${container_name} --image ${MARIADB_IMAGE} -i --rm --restart=Never -- \
        mysql -h "${db_server}" -uroot "-p${db_password}" "${db_name}" < "${db_file}"
done
oc exec -it openstack-galera-0 -c galera -- mysql --user=root --password=${db_server_password_map["default"]} -e \
    "update nova_api.cell_mappings set name='cell1' where name='default';"
oc exec -it openstack-cell1-galera-0 -c galera -- mysql --user=root --password=${db_server_password_map["default"]} -e \
    "delete from nova_cell1.services where host not like '%nova-cell1-%' and services.binary != 'nova-compute';"
----

== Post-checks

Compare the following outputs with the topology specific configuration.
For more information, see xref:pulling-the-openstack-configuration_{context}[Pulling the OpenStack configuration].
//kgilliga: this xref should specifically point to the Get services topology specific configuration module when it's ready.:

* Check that the databases were imported correctly:
+
----
. ~/.source_cloud_exported_variables

# use 'oc exec' and 'mysql -rs' to maintain formatting
dbs=$(oc exec openstack-galera-0 -c galera -- mysql -rs -uroot "-p$PODIFIED_DB_ROOT_PASSWORD" -e 'SHOW databases;')
echo $dbs | grep -Eq '\bkeystone\b'

# ensure neutron db is renamed from ovs_neutron
echo $dbs | grep -Eq '\bneutron\b'
echo $PULL_OPENSTACK_CONFIGURATION_DATABASES | grep -Eq '\bovs_neutron\b'

# ensure nova cell1 db is extracted to a separate db server and renamed from nova to nova_cell1
c1dbs=$(oc exec openstack-cell1-galera-0 -c galera -- mysql -rs -uroot "-p$PODIFIED_DB_ROOT_PASSWORD" -e 'SHOW databases;')
echo $c1dbs | grep -Eq '\bnova_cell1\b'

# ensure default cell renamed to cell1, and the cell UUIDs retained intact
novadb_mapped_cells=$(oc exec openstack-galera-0 -c galera -- mysql -rs -uroot "-p$PODIFIED_DB_ROOT_PASSWORD" \
  nova_api -e 'select uuid,name,transport_url,database_connection,disabled from cell_mappings;')
uuidf='\S{8,}-\S{4,}-\S{4,}-\S{4,}-\S{12,}'
left_behind=$(comm -23 \
  <(echo $PULL_OPENSTACK_CONFIGURATION_NOVADB_MAPPED_CELLS | grep -oE " $uuidf \S+") \
  <(echo $novadb_mapped_cells | tr -s "| " " " | grep -oE " $uuidf \S+"))
changed=$(comm -13 \
  <(echo $PULL_OPENSTACK_CONFIGURATION_NOVADB_MAPPED_CELLS | grep -oE " $uuidf \S+") \
  <(echo $novadb_mapped_cells | tr -s "| " " " | grep -oE " $uuidf \S+"))
test $(grep -Ec ' \S+$' <<<$left_behind) -eq 1
default=$(grep -E ' default$' <<<$left_behind)
test $(grep -Ec ' \S+$' <<<$changed) -eq 1
grep -qE " $(awk '{print $1}' <<<$default) cell1$" <<<$changed

# ensure the registered Nova compute service name has not changed
novadb_svc_records=$(oc exec openstack-cell1-galera-0 -c galera -- mysql -rs -uroot "-p$PODIFIED_DB_ROOT_PASSWORD" \
  nova_cell1 -e "select host from services where services.binary='nova-compute' order by host asc;")
diff -Z <(echo $novadb_svc_records) <(echo $PULL_OPENSTACK_CONFIGURATION_NOVA_COMPUTE_HOSTNAMES)
----

* During the pre/post checks the pod `mariadb-client` might have returned a pod security warning
related to the `restricted:latest` security context constraint. This is due to default security
context constraints and will not prevent pod creation by the admission controller. You'll see a
warning for the short-lived pod but it will not interfere with functionality.
For more information, see https://learn.redhat.com/t5/DO280-Red-Hat-OpenShift/About-pod-security-standards-and-warnings/m-p/32502[About pod security standards and warnings].
