= Autoscaling adoption

Adopting Autoscaling means that an existing `OpenStackControlPlane` CR, where Aodh
services are supposed to be disabled, should be patched to start the service with the
configuration parameters provided by the source environment.

This guide also assumes that:

. A `TripleO` environment (the source Cloud) is running on one side;
. A `SNO` / `CodeReadyContainers` is running on the other side.

== Prerequisites

* Previous Adoption steps completed. MariaDB, Keystone, Heat and Telemetry
should be already adopted.

== Procedure - Autoscaling adoption

Patch OpenStackControlPlane to deploy Autoscaling services:

[,bash]
----
cat << EOF > aodh_patch.yaml
spec:
  autoscaling:
    enabled: true
    prometheus:
      deployPrometheus: false
    aodh:
      customServiceConfig: |
        [DEFAULT]
        debug=true
      secret: osp-secret
      apiImage: "quay.io/podified-antelope-centos9/openstack-aodh-api:current-podified"
      evaluatorImage: "quay.io/podified-antelope-centos9/openstack-aodh-evaluator:current-podified"
      notifierImage: "quay.io/podified-antelope-centos9/openstack-aodh-notifier:current-podified"
      listenerImage: "quay.io/podified-antelope-centos9/openstack-aodh-listener:current-podified"
      passwordSelectors:
      databaseUser: aodh
      databaseInstance: openstack
      memcachedInstance: memcached
EOF
----

____
If you have previously backup your Openstack services configuration file from the old environment:
xref:pull_openstack_configuration.adoc[pull openstack configuration os-diff] you can use os-diff to compare
and make sure the configuration is correct.
____

[,bash]
----
pushd os-diff
./os-diff cdiff --service aodh -c /tmp/collect_tripleo_configs/aodh/etc/aodh/aodh.conf -o aodh_patch.yaml
----

____
This will producre the difference between both ini configuration files.
____

Patch OpenStackControlPlane to deploy Aodh services:

[,bash]
----
oc patch openstackcontrolplane openstack --type=merge --patch-file aodh_patch.yaml
----

== Post-checks

=== If autoscaling services are enabled inspect Aodh pods

[,bash]
----
AODH_POD=`oc get pods -l service=aodh | tail -n 1 | cut -f 1 -d' '`
oc exec -t $AODH_POD -c aodh-api -- cat /etc/aodh/aodh.conf
----

=== Check whether Aodh API service is registered in Keystone

[,bash]
----
openstack endpoint list | grep aodh
| 6a805bd6c9f54658ad2f24e5a0ae0ab6 | regionOne | aodh      | network      | True    | public    | http://aodh-public-openstack.apps-crc.testing  |
| b943243e596847a9a317c8ce1800fa98 | regionOne | aodh      | network      | True    | internal  | http://aodh-internal.openstack.svc:9696        |
| f97f2b8f7559476bb7a5eafe3d33cee7 | regionOne | aodh      | network      | True    | admin     | http://192.168.122.99:9696                     |
----

=== Create sample resources

We can now test that user can create alarms.

[,bash]
----
openstack alarm create \
--name low_alarm \
--type gnocchi_resources_threshold \
--metric cpu \
--resource-id b7ac84e4-b5ca-4f9e-a15c-ece7aaf68987 \
--threshold 35000000000 \
--comparison-operator lt \
--aggregation-method rate:mean \
--granularity 300 \
--evaluation-periods 3 \
--alarm-action 'log:\\' \
--ok-action 'log:\\' \
--resource-type instance
----

=== (TODO)

* Include adopted autoscaling heat templates
* Include adopted Aodh alarm create commands of type prometheus
