[id="adopting-the-key-manager-service_{context}"]

= Barbican adoption

Adopting Barbican means that an existing `OpenStackControlPlane` CR, where Barbican
is initialy disabled, should be patched to start the service with the configuration
parameters provided by the source environment.

When the procedure is over, the expectation is to see the `BarbicanAPI`, `BarbicanWorker`,
`BarbicanKeystoneListener` services are up and running.
`Keystone endpoints` should also be updated and the same crypto plugin of the source Cloud
will be available. If the conditions above are met, the adoption is considered concluded.

____
*NOTE* This procedure configures barbican to use the simple_crypto backend.
Additional backends are available, such as PKCS11 and DogTag, however they are
not supported in this release.
____

== Prerequisites

* Previous Adoption steps completed. Notably, MariaDB, RabbitMQ and Keystone.
should be already adopted.

== Variables

(There are no shell variables necessary currently.)

== Pre-checks

== Procedure - Barbican adoption

* Add the kek secret. In this case we are updating and using osp-secret,
which contains other service passwords:

+
----
oc set data secret/osp-secret "BarbicanSimpleCryptoKEK=$($CONTROLLER1_SSH "python3 -c \"import configparser; c = configparser.ConfigParser(); c.read('/var/lib/config-data/puppet-generated/barbican/etc/barbican/barbican.conf'); print(c['simple_crypto_plugin']['kek'])\"" | base64 -w 0)"
----

* Patch OpenStackControlPlane to deploy Barbican:
+
----
oc patch openstackcontrolplane openstack --type=merge --patch '
spec:
  barbican:
    enabled: true
    apiOverride:
      route: {}
    template:
      databaseInstance: openstack
      databaseUser: barbican
      rabbitMqClusterName: rabbitmq
      secret: osp-secret
      simpleCryptoBackendSecret: osp-secret
      serviceAccount: barbican
      serviceUser: barbican
      passwordSelectors:
        database: BarbicanDatabasePassword
        service: BarbicanPassword
        simplecryptokek: BarbicanSimpleCryptoKEK
      barbicanAPI:
        replicas: 1
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
      barbicanWorker:
        replicas: 1
      barbicanKeystoneListener:
        replicas: 1
'
----

== Post-checks

* See that Keystone endpoints are defined and pointing to the podified
FQDNs:
+
[,bash]
----
openstack endpoint list | grep key-manager
----

=== Check that Barbican API service is registered in Keystone

[,bash]
----
openstack service list | grep key-manager
----

[,bash]
----
openstack endpoint list | grep key-manager
----

=== List secrets

[,bash]
----
openstack secret list
----

**TODO: Once different crypto plugins are supported, additional lines test those should be added.
