= Pull Openstack configuration

Before starting to adoption workflow, we can start by pulling the configuration
from the Openstack services and TripleO on our file system in order to backup
the configuration files and then use it for later, during the configuration of
the adopted services and for the record to compare and make sure nothing has been
missed or misconfigured.

Make sure you have pull the os-diff repository and configure according to your
environment:
link:planning.md#Configuration tooling[Configure os-diff]

== Pull configuration from a TripleO deployment

Before starting you need to update your ssh parameters according to your environment in the os-diff.cfg.
Once it's done, you can start to pull configuration from your OpenStack servies.

All the services are describes in a yaml file:

https://github.com/openstack-k8s-operators/os-diff/config.yaml[config parameters]

You can enable or disable the services you want then you can start to pull the configuration on your local file system:

[,bash]
----
pushd os-diff
./os-diff pull
----

The configuration will be pulled and stored by default:

[,bash]
----
/tmp/tripleo/
----

Once it's done, you should have into your local path a directory per services such as:

----
  ▾ tmp/
    ▾ tripleo/
      ▾ glance/
----
