[id="adopting-telemetry-services_{context}"]

//:context: adopting-telemetry
//kgilliga: This module might be converted to an assembly, or a procedure as a standalone chapter.
//Check xref contexts.

= Adopting Telemetry services

Adopting Telemetry means that an existing `OpenStackControlPlane` CR, where Telemetry services are supposed to be disabled, should be patched to start the service with the configuration parameters provided by the source environment.

This guide also assumes that:

. A `TripleO` environment (the source Cloud) is running on one side;
. A `SNO` / `CodeReadyContainers` is running on the other side.

== Prerequisites

* Previous Adoption steps completed. MariaDB, Keystone and EDPM should be already adopted.

== Procedure - Telemetry adoption

Patch OpenStackControlPlane to deploy Ceilometer services:

----
cat << EOF > ceilometer_patch.yaml
spec:
  ceilometer:
    enabled: true
    template:
      customServiceConfig: |
        [DEFAULT]
        debug=true
      secret: osp-secret
EOF
----

Patch OpenStackControlPlane to deploy Ceilometer services:

----
oc patch openstackcontrolplane openstack --type=merge --patch-file ceilometer_patch.yaml
----

== Post-checks

=== Inspect the resulting Ceilometer pods

----
CEILOMETETR_POD=`oc get pods -l service=ceilometer | tail -n 1 | cut -f 1 -d' '`
oc exec -t $CEILOMETETR_POD -c ceilometer-central-agent -- cat /etc/ceilometer/ceilometer.conf
----

=== Inspect the resulting Ceilometer IPMI agent pod on Data Plane nodes

----
podman ps | grep ceilometer-ipmi
----

=== Inspecting enabled pollsters

----
oc get secret ceilometer-config-data -o jsonpath="{.data['polling\.yaml']}"  | base64 -d
----

=== Enabling pollsters according to requirements

----
cat << EOF > polling.yaml
---
sources:
    - name: pollsters
      interval: 300
      meters:
        - volume.size
        - image.size
        - cpu
        - memory
EOF

oc patch secret ceilometer-config-data  --patch="{\"data\": { \"polling.yaml\": \"$(base64 -w0 polling.yaml)\"}}"
----
