[id="adopting-autoscaling_{context}"]

//:context: adopting-autoscaling
//kgilliga: This module might be converted to an assembly, or a procedure as a standalone chapter.
//Check xref contexts.

= Adopting autoscaling

Adopting autoscaling means that an existing `OpenStackControlPlane` CR, where Aodh services are supposed to be disabled, should be patched to start the service with the configuration parameters provided by the source environment.

This guide also assumes that:

. A `TripleO` environment (the source Cloud) is running on one side;
. A `SNO` / `CodeReadyContainers` is running on the other side.

== Prerequisites

* Previous Adoption steps completed. MariaDB, Keystone, Heat and Telemetry
should be already adopted.

== Procedure - Autoscaling adoption

=== Patch OpenStackControlPlane to deploy autoscaling services:

----
oc patch openstackcontrolplane openstack --type=merge --patch '
spec:
  telemetry:
    enabled: true
    prometheus:
      deployPrometheus: false
    aodh:
      customServiceConfig: |
        [DEFAULT]
        debug=true
      secret: osp-secret
ifeval::["{build}" != "downstream"]
      apiImage: "quay.io/podified-antelope-centos9/openstack-aodh-api:current-podified"
      evaluatorImage: "quay.io/podified-antelope-centos9/openstack-aodh-evaluator:current-podified"
      notifierImage: "quay.io/podified-antelope-centos9/openstack-aodh-notifier:current-podified"
      listenerImage: "quay.io/podified-antelope-centos9/openstack-aodh-listener:current-podified"
endif::[]
ifeval::["{build}" == "downstream"]
      apiImage: "registry.redhat.io/rhosp-dev-preview/openstack-aodh-api-rhel9:18.0"
      evaluatorImage: "registry.redhat.io/rhosp-dev-preview/openstack-aodh-evaluator-rhel9:18.0"
      notifierImage: "registry.redhat.io/rhosp-dev-preview/openstack-aodh-notifier-rhel9:18.0"
      listenerImage: "registry.redhat.io/rhosp-dev-preview/openstack-aodh-listener-rhel9:18.0"
endif::[]
      passwordSelectors:
      databaseUser: aodh
      databaseInstance: openstack
      memcachedInstance: memcached
EOF
----

=== Install cluster-observability-operator

----
oc create -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-observability-operator
  namespace: openshift-operators
spec:
  channel: development
  installPlanApproval: Automatic
  name: cluster-observability-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
EOF
----

=== Wait for the installation to succeed

----
oc wait --for jsonpath="{.status.phase}"=Succeeded csv --namespace=openshift-operators -l operators.coreos.com/cluster-observability-operator.openshift-operators
----

=== Enable metrics storage backend
----
oc patch openstackcontrolplane openstack --type=merge --patch '
spec:
  telemetry:
    enabled: true
    template:
      metricStorage:
        enabled: true
'
----

== Post-checks

=== Verify Aodh pods and service endpoints

----
AODH_POD=`oc get pods -l service=aodh | tail -n 1 | cut -f 1 -d' '`
oc exec -t $AODH_POD -c aodh-api -- cat /etc/aodh/aodh.conf
----

=== Check whether Aodh API service is registered in Keystone

----
openstack endpoint list | grep aodh
| d05d120153cd4f9b8310ac396b572926 | regionOne | aodh  | alarming  | True    | internal  | http://aodh-internal.openstack.svc:8042  |
| d6daee0183494d7a9a5faee681c79046 | regionOne | aodh  | alarming  | True    | public    | http://aodh-public.openstack.svc:8042    |
----

=== Verify metric storage pods are deployed

----
oc get pods -l alertmanager=metric-storage
NAME                            READY   STATUS    RESTARTS   AGE
alertmanager-metric-storage-0   2/2     Running   0          17h
alertmanager-metric-storage-1   2/2     Running   0          17h

oc get pods -l prometheus=metric-storage
NAME                          READY   STATUS    RESTARTS   AGE
prometheus-metric-storage-0   3/3     Running   0          17h
----

//=== (TODO)

//* Include adopted autoscaling heat templates
//* Include adopted Aodh alarm create commands of type prometheus
