[id="adopting-autoscaling_{context}"]

= Adopting Autoscaling services

Adopting autoscaling means that an existing `OpenStackControlPlane` custom resource (CR), where Aodh services are supposed to be disabled, should be patched to start the service with the configuration parameters provided by the source environment.

This guide also assumes that:

. A {OpenStackPreviousInstaller} environment (the source Cloud) is running on one side;
. A `SNO` / `CodeReadyContainers` is running on the other side.

.Prerequisites

* Previous Adoption steps completed. MariaDB, the {identity_service_first_ref}, the {orchestration_first_ref}, and Telemetry
should be already adopted.
//kgilliga: Should this procedure be moved to after the data plane adoption chapter?

.Procedure

. Patch the `OpenStackControlPlane` CR to deploy autoscaling services:
+
----
oc patch openstackcontrolplane openstack --type=merge --patch '
spec:
  telemetry:
    enabled: true
    template:
      autoscaling:
        enabled: true
        aodh:
          passwordSelector:
            aodhService: AodhPassword
          databaseAccount: aodh
          databaseInstance: openstack
          secret: osp-secret
          serviceUser: aodh
        heatInstance: heat
'
----

.Verification

. If autoscaling services are enabled, inspect Aodh pods:
+
----
AODH_POD=`oc get pods -l service=aodh -n openstack | tail -n 1 | cut -f 1 -d' '`
oc exec -t $AODH_POD -c aodh-api -- cat /etc/aodh/aodh.conf
----

. Check whether Aodh API service is registered in {identity_service}:
+
----
openstack endpoint list | grep aodh
| d05d120153cd4f9b8310ac396b572926 | regionOne | aodh  | alarming  | True    | internal  | http://aodh-internal.openstack.svc:8042  |
| d6daee0183494d7a9a5faee681c79046 | regionOne | aodh  | alarming  | True    | public    | http://aodh-public.openstack.svc:8042    |
----

.Autoscaling template adoption

* `PrometheusAlarm` alarm type must be used instead of `GnocchiAggregationByResourcesAlarm`

* Create Aodh alarms of type prometheus
+
----
openstack alarm create --name high_cpu_alarm \
--type prometheus \
--query "(rate(ceilometer_cpu{resource_name=~'cirros'})) * 100" \
--alarm-action 'log://' \
--granularity 15 \
--evaluation-periods 3 \
--comparison-operator gt \
--threshold 7000000000
----

* Verify the state of alarm
+
----
openstack alarm list
+--------------------------------------+------------+------------------+-------------------+----------+
| alarm_id                             | type       | name             | state  | severity | enabled  |
+--------------------------------------+------------+------------------+-------------------+----------+
| 209dc2e9-f9d6-40e5-aecc-e767ce50e9c0 | prometheus | prometheus_alarm |   ok   |    low   |   True   |
+--------------------------------------+------------+------------------+-------------------+----------+
----
