[id="migrating-databases-to-mariadb-instances_{context}"]

//kgilliga: Find out if the steps in the Variables and pre-checks sections can go in the main procedure or if they have to be done before.

= Migrating databases to MariaDB instances

This document describes how to move the databases from the original
{rhos_prev_long} ({OpenStackShort}) deployment to the MariaDB instances in the {OpenShift} cluster.

[NOTE]
This example scenario describes a simple single-cell setup. Real
multi-stack topology recommended for production use results in different
cells DBs layout, and should be using different naming schemes (not covered
here this time).

.Prerequisites

* Make sure the previous Adoption steps have been performed successfully.
 ** The `OpenStackControlPlane` resource must be already created.
 ** The control plane MariaDB and RabbitMQ are running. No other control plane services are running.
 ** Required services specific topology. For more information, see xref:proc_retrieving-topology-specific-service-configuration_migrating-databases[Retrieving topology-specific service configuration].
 ** {OpenStackShort} services have been stopped. For more information, see xref:stopping-openstack-services_{context}[Stopping {rhos_prev_long} services].
 ** There must be network routability between the original MariaDB and the MariaDB for the control plane.
* Define the following shell variables. The values that are used are examples. Replace these example values with values that are correct for your environment:
+
----
ifeval::["{build}" != "downstream"]
STORAGE_CLASS=crc-csi-hostpath-provisioner
MARIADB_IMAGE=quay.io/podified-antelope-centos9/openstack-mariadb:current-podified
endif::[]
ifeval::["{build}" == "downstream"]
STORAGE_CLASS=local-storage
MARIADB_IMAGE=registry.redhat.io/rhosp-dev-preview/openstack-mariadb-rhel9:18.0
endif::[]

CELLS="default cell1 cell2"
DEFAULT_CELL_NAME="cell3"
RENAMED_CELLS="super $DEFAULT_CELL_NAME cell1 cell2"

# The CHARACTER_SET and collation should match the source DB
# if the do not then it will break foreign key relationships
# for any tables that are created in the future as part of db sync
CHARACTER_SET=utf8
COLLATION=utf8_general_ci

declare -A PODIFIED_DB_ROOT_PASSWORD
for CELL in $(echo $RENAMED_CELLS); do
  PODIFIED_DB_ROOT_PASSWORD[$CELL]=$(oc get -o json secret/osp-secret | jq -r .data.DbRootPassword | base64 -d)
done

declare -A PODIFIED_MARIADB_IP
for CELL in $(echo $RENAMED_CELLS); do
  if [ "$CELL" = "super" ]; then
    PODIFIED_MARIADB_IP['super']=$(oc get svc --selector "mariadb/name=openstack" -ojsonpath='{.items[0].spec.clusterIP}')
  else
    PODIFIED_MARIADB_IP[$CELL]=$(oc get svc --selector "mariadb/name=openstack-$CELL" -ojsonpath='{.items[0].spec.clusterIP}')
  fi
done

declare -A TRIPLEO_PASSWORDS
for CELL in $(echo $CELLS); do
  if [ "$CELL" = "default" ]; then
    TRIPLEO_PASSWORDS[default]='~/overcloud-deploy/overcloud/overcloud-passwords.yaml'
  else
    TRIPLEO_PASSWORDS[$CELL]='~/${CELL}/${CELL}-passwords.yaml'
  fi
done

declare -A SOURCE_DB_ROOT_PASSWORD
for CELL in $(echo $CELLS); do
  SOURCE_DB_ROOT_PASSWORD[$CELL]=$(cat ${TRIPLEO_PASSWORDS[$CELL]} | grep ' MysqlRootPassword:' | awk -F ': ' '{ print $2; }')
done

declare -A SOURCE_MARIADB_IP
SOURCE_MARIADB_IP[default]=*<galera cluster VIP>*
SOURCE_MARIADB_IP[cell1]=*<galera cell1 cluster VIP>*
SOURCE_MARIADB_IP[cell2]=*<galera cell2 cluster VIP>*
# ...

declare -A SOURCE_GALERA_MEMBERS_DEFAULT
SOURCE_GALERA_MEMBERS_DEFAULT=(
  ["standalone.localdomain"]=172.17.0.100
  # [...]=...
)
declare -A SOURCE_GALERA_MEMBERS_CELL1
SOURCE_GALERA_MEMBERS_CELL1=(
  # ...
)
declare -A SOURCE_GALERA_MEMBERS_CELL2
SOURCE_GALERA_MEMBERS_CELL2=(
  # ...
)
# ...
----
+
Here, `CELLS` and `RENAMED_CELLS` represent changes that are going to be made
after importing databases: the `default` cell takes a new name from `DEFAULT_CELL_NAME`.
In a multi-cell adoption scenario, it may retain its original 'default' name as well.

Note that the `super` is not a cell, but the top-scope Nova
API "upcall" database instance. A super conductor connects to that database.
In this guide, the upcall and cells databases are going to use the same password
defined in `osp-secret`. Old passwords are only needed to prepare the data exports.

A standalone TripleO only creates a 'default' cell, which should be the only `CELLS` value for such a case
(and `DEFAULT_CELL_NAME` should be `cell1`).

** For each cell defined in `CELLS`
*** Replace `["standalone.localdomain"]="172.17.0.100"`, and complete `SOURCE_GALERA_MEMBERS_*` with the names of MariaDB Galera cluster members and its IP address.
*** Replace `SOURCE_MARIADB_IP[*]= ...`, and complete the records lists for the cell names and VIP addresses of MariaDB Galera clusters.
*** Replace `SOURCE_GALERA_MEMBERS_*[*]= ...`, and complete the records lists for the cell names and IP addresses of MariaDB Galera cluster members.

* Prepare MariaDB copy directory and the adoption helper pod

* Create a temporary folder to store adoption helper pod (pick storage requests to fit MySQL database size):
+
----
mkdir ~/adoption-db
cd ~/adoption-db
----
+
[source,yaml]
----
oc apply -f - <<EOF
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data
spec:
  storageClassName: $STORAGE_CLASS
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: mariadb-copy-data
  annotations:
    openshift.io/scc: anyuid
    k8s.v1.cni.cncf.io/networks: internalapi
  labels:
    app: adoption
spec:
  containers:
  - image: $MARIADB_IMAGE
    command: [ "sh", "-c", "sleep infinity"]
    name: adoption
    volumeMounts:
    - mountPath: /backup
      name: mariadb-data
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ALL
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  volumes:
  - name: mariadb-data
    persistentVolumeClaim:
      claimName: mariadb-data
EOF
----

* Wait for the pod to come up
+
----
oc wait --for condition=Ready pod/mariadb-copy-data --timeout=30s
----

.Procedure

. Check that the source Galera database cluster(s) members are online and synced:
+
----
for CELL in $(echo $CELLS); do
  MEMBERS=SOURCE_GALERA_MEMBERS_$(echo ${CELL}|tr '[:lower:]' '[:upper:]')[@]
  for i in "${!MEMBERS}"; do
    echo "Checking for the database node $i WSREP status Synced"
    oc rsh mariadb-copy-data mysql \
      -h "$i" -uroot -p"${SOURCE_DB_ROOT_PASSWORD[$CELL]}" \
      -e "show global status like 'wsrep_local_state_comment'" | \
      grep -qE "\bSynced\b"
  done
done
----
+
Each additional Nova v2 cell runs a dedicated Galera database cluster, so the checking is done for all of it.

. Get the count of not-OK source databases:
+
----
for CELL in $(echo $CELLS); do
  oc rsh mariadb-copy-data mysql -h "${SOURCE_MARIADB_IP[$CELL]}" -uroot -p"${SOURCE_DB_ROOT_PASSWORD[$CELL]}" -e "SHOW databases;"
end
----

. Run mysqlcheck on the original DB to look for things that are not OK:
+
----
. ~/.source_cloud_exported_variables
test -z "$PULL_OPENSTACK_CONFIGURATION_MYSQLCHECK_NOK[@]" || echo FAILED
----

. Test connection to control plane "upcall" and cells DBs (show databases):
+
----
for CELL in $(echo $RENAMED_CELLS); do
  oc run mariadb-client --image $MARIADB_IMAGE -i --rm --restart=Never -- \
    mysql -rsh "$PODIFIED_MARIADB_IP[$CELL]" -uroot -p"$PODIFIED_DB_ROOT_PASSWORD[$CELL]" -e 'SHOW databases;'
done
----
+
[NOTE]
You need to transition {compute_service_first_ref} services imported later on into a
superconductor architecture. For that, delete the old service records in
cells DBs, starting from the cell1. New records will be registered with
different hostnames provided by the {compute_service} service operator. All {compute_service}
services, except the compute agent, have no internal state, and its service
records can be safely deleted. The former `default` cell will be also renamed to `cell1`.

. Create a dump of the original databases:
+
----
oc rsh mariadb-copy-data << EOF
  for CELL in $(echo $CELLS); do
    mysql -h"${SOURCE_MARIADB_IP[\$CELL]}" -uroot -p"${SOURCE_DB_ROOT_PASSWORD[\$CELL]}" \
    -N -e "show databases" | grep -E -v "schema|mysql|gnocchi" | \
    while read dbname; do
      echo "Dumping \$CELL cell \${dbname}";
      mysqldump -h"${SOURCE_MARIADB_IP[\$CELL]}" -uroot -p"${SOURCE_DB_ROOT_PASSWORD[\$CELL]}" \
        --single-transaction --complete-insert --skip-lock-tables --lock-tables=0 \
        "\${dbname}" > /backup/"\${CELL}.\${dbname}".sql;
    done
  done
EOF
----
+
Note filtering the information and performance schema tables.
Gnocchi is no longer used as a metric store as well

. Restore the databases from .sql files into the control plane MariaDB:
+
----
oc rsh mariadb-copy-data << EOF
  for CELL in $(echo $CELLS); do
    RCELL=$CELL
    [ "$CELL" = "default" ] && RCELL=$DEFAULT_CELL_NAME

    # db schemas to rename on import
    declare -A db_name_map
    db_name_map['nova']="nova_\${RCELL}"
    db_name_map['ovs_neutron']='neutron'
    db_name_map['ironic-inspector']='ironic_inspector'

    # db servers to import into
    declare -A db_server_map
    db_server_map['default']=${PODIFIED_MARIADB_IP['super']}
    db_server_map["nova_\${RCELL}"]=${PODIFIED_MARIADB_IP[\${RCELL}]}

    # db server root password map
    declare -A db_server_password_map
    db_server_password_map['default']=${PODIFIED_DB_ROOT_PASSWORD['super']}
    db_server_password_map["nova_\${RCELL}"]=${PODIFIED_DB_ROOT_PASSWORD[\$RCELL]}

    cd /backup
    for db_file in \$(ls \${CELL}.*.sql); do
      db_name=\$(echo \${db_file} | awk -F'.' '{ print \$2; }')
      renamed_db_file="\${RCELL}_new.\${db_name}.sql"
      mv -f \${db_file} \${renamed_db_file}
      if [[ -v "db_name_map[\${db_name}]" ]]; then
        echo "renaming \$CELL cell \${db_name} to \$RCELL \${db_name_map[\${db_name}]}"
        db_name=\${db_name_map[\${db_name}]}
      fi
      db_server=\${db_server_map["default"]}
      if [[ -v "db_server_map[\${db_name}]" ]]; then
        db_server=\${db_server_map[\${db_name}]}
      fi
      db_password=\${db_server_password_map['default']}
      if [[ -v "db_server_password_map[\${db_name}]" ]]; then
        db_password=\${db_server_password_map[\${db_name}]}
      fi
      echo "creating \$RCELL cell \${db_name} in \${db_server}"
      mysql -h"\${db_server}" -uroot "-p\${db_password}" -e \
        "CREATE DATABASE IF NOT EXISTS \${db_name} DEFAULT \
        CHARACTER SET ${CHARACTER_SET} DEFAULT COLLATE ${COLLATION};"
      echo "importing \$RCELL cell \${db_name} into \${db_server} from \${renamed_db_file}"
      mysql -h "\${db_server}" -uroot "-p\${db_password}" "\${db_name}" < "\${renamed_db_file}"
    done

    if [ "$RCELL" = "$DEFAULT_CELL_NAME" ] ; then
      mysql -h "\${db_server_map['default']}" -uroot -p"\${db_server_password_map['default']}" -e \
        "update nova_api.cell_mappings set name='$DEFAULT_CELL_NAME' where name='default';"
    fi
    mysql -h "\${db_server_map["nova_\${RCELL}"]}" -uroot -p"\${db_server_password_map["nova_\${RCELL}"]}" -e \
      "delete from nova_\${RCELL}.services where host not like '%nova_\${RCELL}-%' and services.binary != 'nova-compute';"
  done
EOF
----

.Verification

Compare the following outputs with the topology specific configuration.
For more information, see xref:proc_retrieving-topology-specific-service-configuration_migrating-databases[Retrieving topology-specific service configuration].

. Check that the databases were imported correctly:
+
----
. ~/.source_cloud_exported_variables
# FIXME: no longer appropriate for mult-cell arrays
# use 'oc exec' and 'mysql -rs' to maintain formatting
dbs=$(oc exec openstack-galera-0 -c galera -- mysql -rs -uroot "-p$PODIFIED_DB_ROOT_PASSWORD" -e 'SHOW databases;')
echo $dbs | grep -Eq '\bkeystone\b'

# ensure neutron db is renamed from ovs_neutron
echo $dbs | grep -Eq '\bneutron\b'
echo $PULL_OPENSTACK_CONFIGURATION_DATABASES[@] | grep -Eq '\bovs_neutron\b'

# ensure nova cell1 db is extracted to a separate db server and renamed from nova to nova_cell1
c1dbs=$(oc exec openstack-cell1-galera-0 -c galera -- mysql -rs -uroot "-p$PODIFIED_DB_ROOT_PASSWORD" -e 'SHOW databases;')
echo $c1dbs | grep -Eq '\bnova_cell1\b'

# ensure default cell renamed to cell1, and the cell UUIDs retained intact
novadb_mapped_cells=$(oc exec openstack-galera-0 -c galera -- mysql -rs -uroot "-p$PODIFIED_DB_ROOT_PASSWORD" \
  nova_api -e 'select uuid,name,transport_url,database_connection,disabled from cell_mappings;')
uuidf='\S{8,}-\S{4,}-\S{4,}-\S{4,}-\S{12,}'
left_behind=$(comm -23 \
  <(echo $PULL_OPENSTACK_CONFIGURATION_NOVADB_MAPPED_CELLS | grep -oE " $uuidf \S+") \
  <(echo $novadb_mapped_cells | tr -s "| " " " | grep -oE " $uuidf \S+"))
changed=$(comm -13 \
  <(echo $PULL_OPENSTACK_CONFIGURATION_NOVADB_MAPPED_CELLS | grep -oE " $uuidf \S+") \
  <(echo $novadb_mapped_cells | tr -s "| " " " | grep -oE " $uuidf \S+"))
test $(grep -Ec ' \S+$' <<<$left_behind) -eq 1
default=$(grep -E ' default$' <<<$left_behind)
test $(grep -Ec ' \S+$' <<<$changed) -eq 1
grep -qE " $(awk '{print $1}' <<<$default) cell1$" <<<$changed

# ensure the registered Compute service name has not changed
novadb_svc_records=$(oc exec openstack-cell1-galera-0 -c galera -- mysql -rs -uroot "-p$PODIFIED_DB_ROOT_PASSWORD" \
  nova_cell1 -e "select host from services where services.binary='nova-compute' order by host asc;")
diff -Z <(echo $novadb_svc_records) <(echo $PULL_OPENSTACK_CONFIGURATION_NOVA_COMPUTE_HOSTNAMES['cell1'])
----

. During the pre/post checks the pod `mariadb-client` might have returned a pod security warning
related to the `restricted:latest` security context constraint. This is due to default security
context constraints and will not prevent pod creation by the admission controller. You'll see a
warning for the short-lived pod but it will not interfere with functionality.
. Delete the `mariadb-data` pod and `mariadb-copy-data` persistent volume claim with databases backup (consider making a snapshot of it, before deleting)
+
----
oc delete pod mariadb-copy-data
oc delete pvc mariadb-data
----
For more information, see https://learn.redhat.com/t5/DO280-Red-Hat-OpenShift/About-pod-security-standards-and-warnings/m-p/32502[About pod security standards and warnings].
