[id="adopting-compute-services-to-the-data-plane_{context}"]

= Adopting Compute services to the {rhos_acro} data plane

.Prerequisites

* Remaining source cloud xref:stopping-infrastructure-management-and-compute-services_{context}[Stopping infrastructure management and Compute services] on Compute hosts.
* Ceph backend for Nova/Libvirt is configured xref:configuring-a-ceph-backend_migrating-databases[Configuring a Ceph backend].
* Make sure the IPAM is configured

----
oc apply -f - <<EOF
apiVersion: network.openstack.org/v1beta1
kind: NetConfig
metadata:
  name: netconfig
spec:
  networks:
  - name: ctlplane
    dnsDomain: ctlplane.example.com
    subnets:
    - name: subnet1
      allocationRanges:
      - end: 192.168.122.120
        start: 192.168.122.100
      - end: 192.168.122.200
        start: 192.168.122.150
      cidr: 192.168.122.0/24
      gateway: 192.168.122.1
  - name: internalapi
    dnsDomain: internalapi.example.com
    subnets:
    - name: subnet1
      allocationRanges:
      - end: 172.17.0.250
        start: 172.17.0.100
      cidr: 172.17.0.0/24
      vlan: 20
  - name: External
    dnsDomain: external.example.com
    subnets:
    - name: subnet1
      allocationRanges:
      - end: 10.0.0.250
        start: 10.0.0.100
      cidr: 10.0.0.0/24
      gateway: 10.0.0.1
  - name: storage
    dnsDomain: storage.example.com
    subnets:
    - name: subnet1
      allocationRanges:
      - end: 172.18.0.250
        start: 172.18.0.100
      cidr: 172.18.0.0/24
      vlan: 21
  - name: storagemgmt
    dnsDomain: storagemgmt.example.com
    subnets:
    - name: subnet1
      allocationRanges:
      - end: 172.20.0.250
        start: 172.20.0.100
      cidr: 172.20.0.0/24
      vlan: 23
  - name: tenant
    dnsDomain: tenant.example.com
    subnets:
    - name: subnet1
      allocationRanges:
      - end: 172.19.0.250
        start: 172.19.0.100
      cidr: 172.19.0.0/24
      vlan: 22
EOF
----

* When `neutron-sriov-nic-agent` is running on the existing Compute nodes, check the physical device mappings and ensure that they match the values that are defined in the `OpenStackDataPlaneNodeSet` custom resource (CR). For more information, see xref:pulling-configuration-from-tripleo-deployment_reviewing-configuration[Pulling the configuration from a {OpenStackPreviousInstaller} deployment].

* Define the shell variables necessary to apply the fast-forward upgrade commands, for each Nova compute cell.
Omit setting `CEPH_FSID`, if the local storage backend is going to be configured by Nova for Libvirt. The storage backend cannot be changed during adoption, and must match the one used on the source cloud:
+
----
PODIFIED_DB_ROOT_PASSWORD=$(oc get -o json secret/osp-secret | jq -r .data.DbRootPassword | base64 -d)
CEPH_FSID=$(oc get secret ceph-conf-files -o json | jq -r '.data."ceph.conf"' | base64 -d | grep fsid | sed -e 's/fsid = //'

alias openstack="oc exec -t openstackclient -- openstack"

DEFAULT_CELL_NAME="cell3"
RENAMED_CELLS="cell1 cell2 $DEFAULT_CELL_NAME"

declare -A COMPUTES_CELL1
export COMPUTES_CELL1=(
  ["standalone.localdomain"]="192.168.122.100"
  # ...
)
declare -A COMPUTES_CELL2
export COMPUTES_CELL2=(
  # ...
)
declare -A COMPUTES_CELL3
export COMPUTES_CELL3=(
  # ...
)
# ...

NODESETS=""
for CELL in $(echo $RENAMED_CELLS); do
  [ "$CELL" = "cell1" ] && continue
  NODESETS="'openstack-${CELL}', $NODESETS"
done
NODESETS="[${NODESETS} 'openstack-cell1']"
----
+
The `default` cell takes a new name from `DEFAULT_CELL_NAME`.
In a multi-cell adoption scenario, it may retain its original 'default' name as well.

A standalone TripleO only creates a 'default' cell, which should be the only `CELLS` value for such a case
(and `DEFAULT_CELL_NAME` should be `cell1`).

** For each cell defined in `CELLS`
*** Replace `["standalone.localdomain"]="192.168.122.100"`, and complete `COMPUTES_CELL_*` with the names of compute nodes and its IP addresses.

.Procedure

ifeval::["{build}" != "downstream"]
. Create a https://kubernetes.io/docs/concepts/configuration/secret/#ssh-authentication-secrets[ssh authentication secret] for the data plane nodes:
//kgilliga:I need to check if we will document this in Red Hat docs.
endif::[]
ifeval::["{build}" != "upstream"]
. Create a ssh authentication secret for the data plane nodes:
endif::[]
+
[subs=+quotes]
----
oc apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
    name: dataplane-adoption-secret
    namespace: openstack
data:
    ssh-privatekey: |
ifeval::["{build}" != "downstream"]
$(cat ~/install_yamls/out/edpm/ansibleee-ssh-key-id_rsa | base64 | sed \'s/^/        /')
endif::[]
ifeval::["{build}" == "downstream"]
$(cat *<path to SSH key>* | base64 | sed \'s/^/        /')
endif::[]
EOF
----

. Generate an ssh key-pair `nova-migration-ssh-key` secret:
+
----
cd "$(mktemp -d)"
ssh-keygen -f ./id -t ecdsa-sha2-nistp521 -N ''
oc get secret nova-migration-ssh-key || oc create secret generic nova-migration-ssh-key \
  -n openstack \
  --from-file=ssh-privatekey=id \
  --from-file=ssh-publickey=id.pub \
  --type kubernetes.io/ssh-auth
rm -f id*
cd -
----

. Create a common for all cells `nova-ceph-extra-config` configmap:
+
[source,yaml]
----
oc apply -f - <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: nova-ceph-extra-config
  namespace: openstack
data:
  19-nova-compute-cells-workarounds.conf: |
    [workarounds]
    disable_compute_service_check_for_ffu=true
EOF
----
+
With that, {rhos_long} dataplane services for Nova cells remove pre-FFU workarounds, and configure Nova Compute
services for a local libvirt storage backend.

. Optional: create a `nova-ceph-extra-config` configmap, which configures a {CephCluster} backend for `libvirt` instead:
+
[source,yaml]
----
oc apply -f - <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: nova-ceph-extra-config
  namespace: openstack
data:
  19-nova-compute-cells-workarounds.conf: |
    [workarounds]
    disable_compute_service_check_for_ffu=true
  03-ceph-nova.conf: |
    [libvirt]
    images_type=rbd
    images_rbd_pool=vms
    images_rbd_ceph_conf=/etc/ceph/ceph.conf
    images_rbd_glance_store_name=default_backend
    images_rbd_glance_copy_poll_interval=15
    images_rbd_glance_copy_timeout=600
    rbd_user=openstack
    rbd_secret_uuid=$CEPH_FSID
EOF
----
+
It removes pre-FFU workarounds and configures Compute services for the same {CephCluster} backend.
Different storage configuration requires custom config maps named like `nova-cell*-extra-config`.

. Create a custom dataplane service for each additional cell, but `cell1`
+
[source,yaml]
----
for CELL in $(echo $RENAMED_CELLS); do
  if [ "$CELL" = "cell1" ]; then
    # Example: NOVA_EDPM_SERVICE="nova-cell1-custom"
    continue
  else
    NOVA_EDPM_SERVICE="nova-$CELL"
  fi
  oc apply -f - <<EOF
---
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: $NOVA_EDPM_SERVICE
spec:
  dataSources:
    - secretRef:
        name: ${NOVA_EDPM_SERVICE}-compute-config
    - secretRef:
        name: nova-migration-ssh-key
    - configMapRef:
        name: nova-ceph-extra-config
        optional: true
  playbook: osp.edpm.nova
  caCerts: combined-ca-bundle
  edpmServiceType: nova
  containerImageFields:
  - NovaComputeImage
  - EdpmIscsidImage
EOF
  done
----
+
Note that `cell1` is already managed with the default `OpenStackDataPlaneService` called `nova`.
We would not need a custom service to re-configure it for {CephCluster} backend for libvirt.
However, in order to reconfigure its default `spec` data, you will need to create a copy of it as a custom service
as well. No in-place patching allowed as all changes to it will be lost, when the {rhos_long} operator
gets updated with OLM.

For example, to opt out TLS, create it omitting the `spec.caCerts` (the change
will also be needed for others cells services and {rhos_long} controlplane CR).

The secret `nova-cell*-compute-config` is auto-generated for each node-set. You must always specify that secretname
alongside `nova-migration-ssh-key`, `nova-ceph-extra-config`, and any other cell-specific configurations,
for each custom `OpenStackDataPlaneService`.

To enable local cells metadata services, set `spec.dataSources.secretRef` in `OpenStackDataPlaneService` CRs to reference
additional auto-generated `nova-cell*-metadata-neutron-config` secrets (you should have also set
`spec.nova.template.cellTemplates.cell*.metadataServiceTemplate.enable` in `OpenStackControlPlane` CR earlier).

When a cell spans multiple node-sets (not covered here), you would name the custom `OpenStackDataPlaneService` resources like
`nova-cell1-nfv` and `nova-cell1-enterprise`. Then the auto-generated configmaps would be named
`nova-cell1-nfv-extra-config` and `nova-cell1-enterprise-extra-config`.

ifeval::["{build}" == "downstream"]
. Create a secret for the subscription manager and a secret for the Red Hat registry:
+
[source,yaml]
----
oc apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: subscription-manager
data:
  username: <base64 encoded subscription-manager username>
  password: <base64 encoded subscription-manager password>
---
apiVersion: v1
kind: Secret
metadata:
  name: redhat-registry
data:
  username: <base64 encoded registry username>
  password: <base64 encoded registry password>
EOF
----
endif::[]
+
Note that this secret does not need to be referenced in `OpenStackDataPlaneService` objects' `spec.dataSources` data.
It is passed in via a node-specific `OpenStackDataPlaneNodeSet` data in `spec.nodeTemplate.ansible.ansibleVarsFrom`.


* Create the `OpenStackDataPlaneNodeSet` CRs for each Nova compute cell:

+
. If TLS Everywhere is enabled, change spec:tlsEnabled to true
. If using a custom DNS Domain, modify the spec:nodes:[NODE NAME]:hostName to use fqdn for the node.
. Use node set names, like `openstack-cell1`, `openstack-cell2`.
. Assign all compute nodes from the source cloud `default` cell into `openstack-<X>`,
where `<X>` is defined in the `DEFAULT_CELL_NAME` environment variable.
. Assign all compute nodes from the source cloud `cell1` cell into `openstack-cell1` node-set, and so on.
. Different configurations for nodes in multiple node sets of the same cell are not covered in this guide.
+
[source,yaml]
----
for CELL in $(echo $RENAMED_CELLS); do
  if [ "$CELL" = "cell1" ]; then
    # Example: NOVA_EDPM_SERVICE="nova-cell1-custom"
    NOVA_EDPM_SERVICE="nova"
    OSDPNS="openstack"
  else
    NOVA_EDPM_SERVICE="nova-$CELL"
    OSDPNS="openstack-$CELL"
  fi

  computes=COMPUTES_$(echo ${CELL}|tr '[:lower:]' '[:upper:]')[@]
  for compute in $computes; do
    ip=COMPUTES_$(echo ${CELL}|tr '[:lower:]' '[:upper:]')[compute]
    rm -f computes
    cat >> computes << EOF
    ${compute}:
      hostName: $compute
      ansible:
        ansibleHost: $compute
      networks:
      - defaultRoute: true
        fixedIP: ${!ip}
        name: ctlplane
        subnetName: subnet1
      - name: internalapi
        subnetName: subnet1
      - name: storage
        subnetName: subnet1
      - name: tenant
        subnetName: subnet1
    EOF
  done

  cat > nodeset-${CELL}.yaml <<EOF
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNodeSet
metadata:
  name: $OSDPNS
spec:
  tlsEnabled: false
  networkAttachments:
      - ctlplane
  preProvisioned: true
  services:
    - bootstrap
    - download-cache
    - configure-network
    - validate-network
    - install-os
    - configure-os
    - ssh-known-hosts
    - run-os
    - reboot-os
    - install-certs
    - libvirt
    - $NOVA_EDPM_SERVICE
    - ovn
    - neutron-metadata
  env:
    - name: ANSIBLE_CALLBACKS_ENABLED
      value: "profile_tasks"
    - name: ANSIBLE_FORCE_COLOR
      value: "True"
  nodeTemplate:
    ansibleSSHPrivateKeySecret: dataplane-adoption-secret
    ansible:
      ansibleUser: root
ifeval::["{build}" == "downstream"]
      ansibleVarsFrom:
      - prefix: subscription_manager_
        secretRef:
          name: subscription-manager
      - prefix: registry_
        secretRef:
          name: redhat-registry
endif::[]
      ansibleVars:
        edpm_bootstrap_release_version_package: []
        # edpm_network_config
        # Default nic config template for a EDPM node
        # These vars are edpm_network_config role vars
        edpm_network_config_template: |
           ---
           {% set mtu_list = [ctlplane_mtu] %}
           {% for network in nodeset_networks %}
           {{ mtu_list.append(lookup('vars', networks_lower[network] ~ '_mtu')) }}
           {%- endfor %}
           {% set min_viable_mtu = mtu_list | max %}
           network_config:
           - type: ovs_bridge
             name: {{ neutron_physical_bridge_name }}
             mtu: {{ min_viable_mtu }}
             use_dhcp: false
             dns_servers: {{ ctlplane_dns_nameservers }}
             domain: {{ dns_search_domains }}
             addresses:
             - ip_netmask: {{ ctlplane_ip }}/{{ ctlplane_cidr }}
             routes: {{ ctlplane_host_routes }}
             members:
             - type: interface
               name: nic1
               mtu: {{ min_viable_mtu }}
               # force the MAC address of the bridge to this interface
               primary: true
           {% for network in nodeset_networks %}
             - type: vlan
               mtu: {{ lookup('vars', networks_lower[network] ~ '_mtu') }}
               vlan_id: {{ lookup('vars', networks_lower[network] ~ '_vlan_id') }}
               addresses:
               - ip_netmask:
                   {{ lookup('vars', networks_lower[network] ~ '_ip') }}/{{ lookup('vars', networks_lower[network] ~ '_cidr') }}
               routes: {{ lookup('vars', networks_lower[network] ~ '_host_routes') }}
           {% endfor %}

        edpm_network_config_hide_sensitive_logs: false
        #
        # These vars are for the network config templates themselves and are
        # considered EDPM network defaults.
        neutron_physical_bridge_name: br-ctlplane
        neutron_public_interface_name: eth0

        # edpm_nodes_validation
        edpm_nodes_validation_validate_controllers_icmp: false
        edpm_nodes_validation_validate_gateway_icmp: false

        # edpm ovn-controller configuration
        edpm_ovn_bridge_mappings: <bridge_mappings>
        edpm_ovn_bridge: br-int
        edpm_ovn_encap_type: geneve
        ovn_monitor_all: true
        edpm_ovn_remote_probe_interval: 60000
        edpm_ovn_ofctrl_wait_before_clear: 8000

        timesync_ntp_servers:
ifeval::["{build}" != "downstream"]
        - hostname: pool.ntp.org
endif::[]
ifeval::["{build}" == "downstream"]
        - hostname: clock.redhat.com
        - hostname: clock2.redhat.com
endif::[]

ifeval::["{build}" != "downstream"]
        edpm_bootstrap_command: |
          # This is a hack to deploy RDO Delorean repos to RHEL as if it were Centos 9 Stream
          set -euxo pipefail
          curl -sL https://github.com/openstack-k8s-operators/repo-setup/archive/refs/heads/main.tar.gz | tar -xz
          python3 -m venv ./venv
          PBR_VERSION=0.0.0 ./venv/bin/pip install ./repo-setup-main
          # This is required for FIPS enabled until trunk.rdoproject.org
          # is not being served from a centos7 host, tracked by
          # https://issues.redhat.com/browse/RHOSZUUL-1517
          dnf -y install crypto-policies
          update-crypto-policies --set FIPS:NO-ENFORCE-EMS
          # FIXME: perform dnf upgrade for other packages in EDPM ansible
          # here we only ensuring that decontainerized libvirt can start
          ./venv/bin/repo-setup current-podified -b antelope -d centos9 --stream
          dnf -y upgrade openstack-selinux
          rm -f /run/virtlogd.pid
          rm -rf repo-setup-main
endif::[]
ifeval::["{build}" == "downstream"]
        edpm_bootstrap_command: |
          subscription-manager register --username {{ subscription_manager_username }} --password {{ subscription_manager_password }}
          subscription-manager release --set=9.2
          subscription-manager repos --disable=*
          subscription-manager repos --enable=rhel-9-for-x86_64-baseos-eus-rpms --enable=rhel-9-for-x86_64-appstream-eus-rpms --enable=rhel-9-for-x86_64-highavailability-eus-rpms --enable=openstack-17.1-for-rhel-9-x86_64-rpms --enable=fast-datapath-for-rhel-9-x86_64-rpms --enable=openstack-dev-preview-for-rhel-9-x86_64-rpms
          # FIXME: perform dnf upgrade for other packages in EDPM ansible
          # here we only ensuring that decontainerized libvirt can start
          dnf -y upgrade openstack-selinux
          rm -f /run/virtlogd.pid
          podman login -u {{ registry_username }} -p {{ registry_password }} registry.redhat.io
endif::[]

        gather_facts: false
        # edpm firewall, change the allowed CIDR if needed
        edpm_sshd_configure_firewall: true
        edpm_sshd_allowed_ranges: ['192.168.122.0/24']

        # Do not attempt OVS major upgrades here
        edpm_ovs_packages:
        - openvswitch3.1
  nodes:
EOF
  # complete the generated nodes lists
  cat computes >> nodeset-${CELL}.yaml
done
----
+
If any `spec` data changes should be done to the default `nova` service for `cell1`,
change `NOVA_EDPM_SERVICE` to reference its custom `OpenStackDataPlaneService` service
that have been created earlier (like the provided `nova-cell1-custom` example).

* FIXME: missing commands to check ovs external-ids with os-diff before deployment

* Deploy the `OpenStackDataPlaneNodeSet` CRs for each Nova compute cell
+
----
for CELL in $(echo $RENAMED_CELLS); do
  oc apply -f nodeset-${CELL}.yaml
done
----
* Prepare adopted EDPM workloads to use {CephCluster} backend for {block_storage_first_ref}, if configured so
+
[source,yaml]
----
for CELL in $(echo $RENAMED_CELLS); do
  if [ "$CELL" = "cell1" ]; then
    # Example: NOVA_EDPM_SERVICE="nova-cell1-custom"
    NOVA_EDPM_SERVICE="nova"
    OSDPNS="openstack"
  else
    NOVA_EDPM_SERVICE="nova-$CELL"
    OSDPNS="openstack-$CELL"
  fi

  oc patch osdpns/$OSDPNS --type=merge --patch "
  spec:
    services:
      - repo-setup
      - download-cache
      - bootstrap
      - configure-network
      - validate-network
      - install-os
      - configure-os
      - run-os
      - reboot-os
      - install-certs
      - ceph-client
      - libvirt
      - $NOVA_EDPM_SERVICE
      - ovn
      - neutron-metadata
    nodeTemplate:
      extraMounts:
      - extraVolType: Ceph
        volumes:
        - name: ceph
          secret:
            secretName: ceph-conf-files
        mounts:
        - name: ceph
          mountPath: "/etc/ceph"
          readOnly: true
  "
done
----
Note that you should retain the original `OpenStackDataPlaneNodeSet` services
composition, except the inserted `ceph-client` service.

+ Ensure that the `ovn-controller` settings that are configured in the `OpenStackDataPlaneNodeSet` CR are the same as were set in the Compute nodes before adoption. This configuration is stored in the `external_ids` column in the `Open_vSwitch` table in the Open vSwitch database:
+
----
ovs-vsctl list Open .
...
external_ids        : {hostname=standalone.localdomain, ovn-bridge=br-int, ovn-bridge-mappings=<bridge_mappings>, ovn-chassis-mac-mappings="datacentre:1e:0a:bb:e6:7c:ad", ovn-encap-ip="172.19.0.100", ovn-encap-tos="0", ovn-encap-type=geneve, ovn-match-northd-version=False, ovn-monitor-all=True, ovn-ofctrl-wait-before-clear="8000", ovn-openflow-probe-interval="60", ovn-remote="tcp:ovsdbserver-sb.openstack.svc:6642", ovn-remote-probe-interval="60000", rundir="/var/run/openvswitch", system-id="2eec68e6-aa21-4c95-a868-31aeafc11736"}
...
----

+
* Replace `<bridge_mappings>` with the value of the bridge mappings in your configuration, for example, `"datacentre:br-ctlplane"`.

. Optional: Enable `neutron-sriov-nic-agent` in the `OpenStackDataPlaneNodeSet` CR:
+
[source,yaml]
----
oc patch openstackdataplanenodeset openstack --type='json' --patch='[
  {
    "op": "add",
    "path": "/spec/services/-",
    "value": "neutron-sriov"
  }, {
    "op": "add",
    "path": "/spec/nodeTemplate/ansible/ansibleVars/edpm_neutron_sriov_agent_SRIOV_NIC_physical_device_mappings",
    "value": "dummy_sriov_net:dummy-dev"
  }, {
    "op": "add",
    "path": "/spec/nodeTemplate/ansible/ansibleVars/edpm_neutron_sriov_agent_SRIOV_NIC_resource_provider_bandwidths",
    "value": "dummy-dev:40000000:40000000"
  }, {
    "op": "add",
    "path": "/spec/nodeTemplate/ansible/ansibleVars/edpm_neutron_sriov_agent_SRIOV_NIC_resource_provider_hypervisors",
    "value": "dummy-dev:standalone.localdomain"
  }
]'
----

. Optional: Enable `neutron-dhcp` in the `OpenStackDataPlaneNodeSet` CR:
+
[source,yaml]
----
oc patch openstackdataplanenodeset openstack --type='json' --patch='[
  {
    "op": "add",
    "path": "/spec/services/-",
    "value": "neutron-dhcp"
  }]'
----

. Run pre-adoption validation:

.. Create the validation service:
+
[source,yaml]
----
oc apply -f - <<EOF
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: pre-adoption-validation
spec:
  playbook: osp.edpm.pre_adoption_validation
EOF
----

.. Create a `OpenStackDataPlaneDeployment` CR that runs the validation only:
+
[source,yaml]
----
oc apply -f - <<EOF
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneDeployment
metadata:
  name: openstack-pre-adoption
spec:
  nodeSets: $NODESETS
  servicesOverride:
  - pre-adoption-validation
EOF
----
+
Wait for the validation to finish.

.. Confirm that all the Ansible EE pods reach a `Completed` status:
+
----
# watching the pods
watch oc get pod -l app=openstackansibleee
----
+
----
# following the ansible logs with:
oc logs -l app=openstackansibleee -f --max-log-requests 20
----

.. Wait for the deployment to reach the `Ready` status:
+
----
oc wait --for condition=Ready openstackdataplanedeployment/openstack-pre-adoption --timeout=10m
----

. If any openstack-pre-adoption validations fail, you must first determine
which ones were unsuccessful based on the ansible logs and then follow the
instructions below for each case:

* if the hostname validation failed then check that the hostname of the EDPM
node is correctly listed in the `OpenStackDataPlaneNodeSet`

* if the kernel argument check failed then make sure that the
`OpenStackDataPlaneNodeSet` has the same kernel argument configuration in
`edpm_kernel_args` and `edpm_kernel_hugepages` variables than what is used in
the 17 node.

* if the tuned profile check failed then make sure that the
`edpm_tuned_profile` variable in the `OpenStackDataPlaneNodeSet` is configured
to use the same profile as set on the (source) OSP 17 node.

. Remove leftover {OpenStackPreviousInstaller} services

.. Create cleanup data plane service
+
[source,yaml]
---
oc apply -f - <<EOF
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: tripleo-cleanup
spec:
  playbook: osp.edpm.tripleo_cleanup
EOF
---

.. Create OpenStackDataPlaneDeployment to run cleanup
+
[source,yaml]
---
oc apply -f - <<EOF
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneDeployment
metadata:
  name: tripleo-cleanup
spec:
  nodeSets: $NODESETS
  servicesOverride:
  - tripleo-cleanup
EOF
---

.. Wait for the removal to finish.

. Deploy the `OpenStackDataPlaneDeployment` CR:
+
[source,yaml]
----
oc apply -f - <<EOF
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneDeployment
metadata:
  name: openstack
spec:
  nodeSets: $NODESETS
EOF
----

Note: if you have other node sets to deploy (e.g. for networker nodes), you may
add them above in `nodeSets` list, or create separate
`OpenStackDataPlaneDeployment` CRs later.

Note that once a `OpenStackDataPlaneDeployment` CR is deployed, it's impossible
to add new node sets to it later.

.Verification

. Confirm that all the Ansible EE pods reach a `Completed` status:
+
----
# watching the pods
watch oc get pod -l app=openstackansibleee
----
+
----
# following the ansible logs with:
oc logs -l app=openstackansibleee -f --max-log-requests 20
----

. Wait for the data plane deployemt finished:
+
----
oc wait --for condition=Ready openstackdataplanedeployment/openstack --timeout=120m
----
+
If it failed, you can get the list of failed ansible jobs:
+
----
ALLOWED_JOB_RETRIES=3
DEPLOYMENT_NAME=openstack
oc get jobs -l openstackdataplanedeployment=$DEPLOYMENT_NAME -o jsonpath="{.items[?(@.status.failed > $ALLOWED_JOB_RETRIES)].metadata.name}"
----

. Verify that {networking_first_ref} agents are alive:
+
----
oc exec openstackclient -- openstack network agent list
+--------------------------------------+------------------------------+------------------------+-------------------+-------+-------+----------------------------+
| ID                                   | Agent Type                   | Host                   | Availability Zone | Alive | State | Binary                     |
+--------------------------------------+------------------------------+------------------------+-------------------+-------+-------+----------------------------+
| 174fc099-5cc9-4348-b8fc-59ed44fcfb0e | DHCP agent                   | standalone.localdomain | nova              | :-)   | UP    | neutron-dhcp-agent         |
| 10482583-2130-5b0d-958f-3430da21b929 | OVN Metadata agent           | standalone.localdomain |                   | :-)   | UP    | neutron-ovn-metadata-agent |
| a4f1b584-16f1-4937-b2b0-28102a3f6eaa | OVN Controller agent         | standalone.localdomain |                   | :-)   | UP    | ovn-controller             |
+--------------------------------------+------------------------------+------------------------+-------------------+-------+-------+----------------------------+
----

[NOTE]
====
After the data plane adoption, the cell controllers should be decomissioned.
They may become new cell compute nodes by reprovisioning and scaling-out
node sets of the corresponding cells, or adding them into new node sets of each cell
(not covered in this guide).
====