[id="adopting-telemetry-services_{context}"]

= Adopting Telemetry services

Adopting Telemetry means that an existing `OpenStackControlPlane` custom resource (CR), where Telemetry services are supposed to be disabled, should be patched to start the service with the configuration parameters provided by the source environment.

This guide also assumes that:

. A {OpenStackPreviousInstaller} environment (the source Cloud) is running on one side;
. A `SNO` / `CodeReadyContainers` is running on the other side.

.Prerequisites

* Previous Adoption steps completed. MariaDB, the {identity_service_first_ref} and the data plane should be already adopted.
//kgilliga:Should this procedure be moved after the "Adopting the data plane" chapter?

.Procedure

. Patch the `OpenStackControlPlane` CR to deploy Ceilometer services:
// TODO(jistr): There are still some quay.io images in the downstream build.
+
----
oc patch openstackcontrolplane openstack --type=merge --patch '
spec:
  telemetry:
    enabled: true
    template:
      ceilometer:
        enabled: true
        passwordSelector:
          aodhService: AodhPassword
          ceilometerService: CeilometerPassword
        rabbitMqClusterName: rabbitmq
        secret: osp-secret
        serviceUser: ceilometer
EOF
----

. Optional: If you previously backed up your {OpenStackShort} services configuration file from the old environment, you can use os-diff to compare and make sure the configuration is correct. This will produce the difference between both ini configuration files:
+
----
os-diff diff /tmp/collect_tripleo_configs/ceilometer/etc/ceilometer/ceilometer.conf ceilometer_patch.yaml --crd
----
+
For more information, see xref:reviewing-the-openstack-control-plane-configuration_{context}[Reviewing the {rhos_prev_long} control plane configuration].


.Verification

. Inspect the resulting Ceilometer pods:
+
----
CEILOMETETR_POD=`oc get pods -l service=ceilometer | tail -n 1 | cut -f 1 -d' '`
oc exec -t $CEILOMETETR_POD -c ceilometer-central-agent -- cat /etc/ceilometer/ceilometer.conf
----

. Inspect the resulting Ceilometer IPMI agent pod on data plane nodes:
+
----
podman ps | grep ceilometer-ipmi
----

. Inspect enabled pollsters:
+
----
oc get secret ceilometer-config-data -o jsonpath="{.data['polling\.yaml']}"  | base64 -d
----

. Enable pollsters according to requirements:
+
----
cat << EOF > polling.yaml
---
sources:
    - name: pollsters
      interval: 300
      meters:
        - volume.size
        - image.size
        - cpu
        - memory.usage
EOF
----

. Update ceilometer configuration with new pollsters:
+
----
oc patch secret ceilometer-config-data  --patch="{\"data\": { \"polling.yaml\": \"$(base64 -w0 polling.yaml)\"}}"
----
