[id="completing-prerequisites-for-rbd-migration_{context}"]

= Completing prerequisites for a {Ceph} RBD migration

Complete the following prerequisites before you begin the {Ceph} Rados Block Device (RBD) migration.

* The target CephStorage or ComputeHCI nodes are configured to have both `storage` and `storage_mgmt` networks. This ensures that you can use both {Ceph} public and cluster networks from the same node. From {rhos_prev_long} {rhos_prev_ver} and later you do not have to run a stack update.
* NFS Ganesha is migrated from a {OpenStackPreviousInstaller} deployment to `cephadm`. For more information, see xref:creating-a-ceph-nfs-cluster_ceph-prerequisites[Creating an NFS Ganesha
cluster].
* Ceph Metadata Server, monitoring stack, Ceph Object Gateway, and any other daemon that is deployed on Controller nodes.
ifeval::["{build}" != "upstream"]
* The daemons distribution follows the cardinality constraints that are
described in link:https://access.redhat.com/articles/1548993[Red Hat Ceph
Storage: Supported configurations].
endif::[]
* The {Ceph} cluster is healthy, and the `ceph -s` command returns `HEALTH_OK`.
* Run `os-net-config` on the bare metal node and configure additional networks:
.. If target nodes are `CephStorage`, ensure that the network is defined in the
bare metal file for the `CephStorage` nodes, for example, `/home/stack/composable_roles/network/baremetal_deployment.yaml`:
+
[source,yaml]
----
- name: CephStorage
count: 2
instances:
- hostname: oc0-ceph-0
name: oc0-ceph-0
- hostname: oc0-ceph-1
name: oc0-ceph-1
defaults:
networks:
- network: ctlplane
vif: true
- network: storage_cloud_0
subnet: storage_cloud_0_subnet
- network: storage_mgmt_cloud_0
subnet: storage_mgmt_cloud_0_subnet
network_config:
template: templates/single_nic_vlans/single_nic_vlans_storage.j2
----
.. Add the missing network:
+
----
$ openstack overcloud node provision \
-o overcloud-baremetal-deployed-0.yaml --stack overcloud-0 \
/--network-config -y --concurrency 2 /home/stack/metalsmith-0.yaml
----
  .. Verify that the storage network is configured on the target nodes:
+
----
(undercloud) [stack@undercloud ~]$ ssh heat-admin@192.168.24.14 ip -o -4 a
1: lo    inet 127.0.0.1/8 scope host lo\       valid_lft forever preferred_lft forever
5: br-storage    inet 192.168.24.14/24 brd 192.168.24.255 scope global br-storage\       valid_lft forever preferred_lft forever
6: vlan1    inet 192.168.24.14/24 brd 192.168.24.255 scope global vlan1\       valid_lft forever preferred_lft forever
7: vlan11    inet 172.16.11.172/24 brd 172.16.11.255 scope global vlan11\       valid_lft forever preferred_lft forever
8: vlan12    inet 172.16.12.46/24 brd 172.16.12.255 scope global vlan12\       valid_lft forever preferred_lft forever
----
