:_mod-docs-content-type: CONCEPT
[id="reusing-existing-subnet-ranges_{context}"]

= Reusing existing subnet ranges

[role="_abstract"]
Configure new control plane services to reuse the subnets from the {rhos_prev_long} ({OpenStackShort}) environment, and to exclude IP addresses that are already allocated to existing cluster nodes. This avoids additional link local route configuration between the existing and new subnets.

ifeval::["{build_variant}" != "ospdo"]
If your existing subnets do not have enough IP addresses in the existing subnet ranges for the new control plane services, you must create new subnet ranges.
endif::[]

No special routing configuration is required to reuse subnet ranges. However, you must ensure that the IP addresses that are consumed by {OpenStackShort} services do not overlap with the new allocation pools configured for {rhos_long_noacro} control plane services.

If you are especially constrained by the size of the existing subnet, you may
have to apply elaborate exclusion rules when defining allocation pools for the
new control plane services.

[role="_additional-resources"]
.Additional resources
ifeval::["{build_variant}" != "ospdo"]
* xref:using-new-subnet-ranges_{context}[Using new subnet ranges]
endif::[]
* xref:configuring-isolated-networks_configuring-network[Configuring isolated networks]
