[id="deploying-file-systems-service-control-plane_{context}"]

= Deploying the {rhos_component_storage_file} control plane

Copy the {rhos_component_storage_file_first_ref} configuration from the {rhos_prev_long} {rhos_prev_ver} deployment, and then deploy the {rhos_component_storage_file} on the control plane.

.Prerequisites

* Ensure that {rhos_component_storage_file} systemd services (`api`, `cron`, `scheduler`) are
stopped. For more information, see xref:stopping-openstack-services_migrating-databases[Stopping {rhos_prev_long} services].
* If the deployment uses CephFS through NFS as a storage backend, ensure that
pacemaker ordering and collocation constraints are adjusted. For more
information, see xref:stopping-openstack-services_migrating-databases[Stopping {rhos_prev_long} services].
* Ensure that the {rhos_component_storage_file} pacemaker service (`openstack-manila-share`) is
stopped. For more information, see xref:stopping-openstack-services_migrating-databases[Stopping {rhos_prev_long} services].
* Ensure that the database migration has completed. For more information, see xref:migrating-databases-to-mariadb-instances_migrating-databases[Migrating databases to MariaDB instances].
* Ensure that {OpenShift} nodes where `manila-share` service will be deployed
can reach the management network that the storage system is in.
* If the deployment uses CephFS through NFS as a storage backend, ensure that
a new clustered Ceph NFS service is deployed on the Ceph cluster with the help
of Ceph orchestrator. For more information, see
xref:creating-a-ceph-nfs-cluster_migrating-databases[Creating a Ceph NFS cluster].
* Ensure that services such as keystone and memcached are available prior to
adopting the Shared File Systems services.
* If tenant-driven networking was enabled (`driver_handles_share_servers=True`),
ensure that neutron has been deployed prior to adopting Shared File Systems services.

.Procedure

. Define the `CONTROLLER1_SSH` environment variable, if it link:stop_openstack_services.md#variables[hasn't been
defined] already. Then copy the configuration file from {OpenStackShort} {rhos_prev_ver} for
reference.
+
----
$CONTROLLER1_SSH cat /var/lib/config-data/puppet-generated/manila/etc/manila/manila.conf | awk '!/^ *#/ && NF' > ~/manila.conf
----

. Review this configuration alongside any configuration changes that were noted since {OpenStackShort} {rhos_prev_ver}. Not all of it makes sense to bring into the new cloud environment:
// - TODO link config diff tables for RHOSP 17.1 (Wallaby) to RHOSP 18 (Antelope) -
//kgilliga: The following list might need to be placed in its own module and linked here. This is too much text for a procedure.
* The {rhos_component_storage_file} operator is capable of setting up database related configuration
(`[database]`), service authentication (`auth_strategy`,
`[keystone_authtoken]`), message bus configuration
(`transport_url`, `control_exchange`), the default paste config
(`api_paste_config`) and inter-service communication configuration (
`[neutron]`, `[nova]`, `[cinder]`, `[glance]` `[oslo_messaging_*]`). So
all of these can be ignored.
* Ignore the `osapi_share_listen` configuration. In {rhos_long} {rhos_curr_ver}, you rely on
{OpenShift} routes and ingress.
* Pay attention to policy overrides. In {rhos_acro} {rhos_curr_ver}, the {rhos_component_storage_file} ships with a secure
default RBAC, and overrides may not be necessary. Please review RBAC
defaults by using the https://docs.openstack.org/oslo.policy/latest/cli/oslopolicy-policy-generator.html[Oslo policy generator]
tool. If a custom policy is necessary, you must provide it as a
`ConfigMap`. The following sample spec illustrates how a
`ConfigMap` called `manila-policy` can be set up with the contents of a
file called `policy.yaml`.
+
[source,yaml]
----
  spec:
    manila:
      enabled: true
      template:
        manilaAPI:
          customServiceConfig: |
             [oslo_policy]
             policy_file=/etc/manila/policy.yaml
        extraMounts:
        - extraVol:
          - extraVolType: Undefined
            mounts:
            - mountPath: /etc/manila/
              name: policy
              readOnly: true
            propagation:
            - ManilaAPI
            volumes:
            - name: policy
              projected:
                sources:
                - configMap:
                    name: manila-policy
                    items:
                      - key: policy
                        path: policy.yaml
----

* You must preserve the value of the `host` option under the `[DEFAULT]`
section as `hostgroup`.
* The {rhos_component_storage_file} API service needs the `enabled_share_protocols` option to be
added in the `customServiceConfig` section in `manila: template: manilaAPI`.
* If you had scheduler overrides, add them to the `customServiceConfig`
section in `manila: template: manilaScheduler`.
* If you had multiple storage backend drivers configured with {OpenStackShort} {rhos_prev_ver},
you will need to split them up when deploying {rhos_acro} {rhos_curr_ver}. Each storage
backend driver needs to use its own instance of the `manila-share`
service.
* If a storage backend driver needs a custom container image, find it on the
https://catalog.redhat.com/software/containers/search?gs&q=manila[RHOSP Ecosystem Catalog]
and set `manila: template: manilaShares: <custom name> : containerImage`
value. The following example illustrates multiple storage backend drivers,
using custom container images.
+
[source,yaml]
----
  spec:
    manila:
      enabled: true
      template:
        manilaAPI:
          customServiceConfig: |
            [DEFAULT]
            enabled_share_protocols = nfs
          replicas: 3
        manilaScheduler:
          replicas: 3
        manilaShares:
         netapp:
           customServiceConfig: |
             [DEFAULT]
             debug = true
             enabled_share_backends = netapp
             host = hostgroup
             [netapp]
             driver_handles_share_servers = False
             share_backend_name = netapp
             share_driver = manila.share.drivers.netapp.common.NetAppDriver
             netapp_storage_family = ontap_cluster
             netapp_transport_type = http
           replicas: 1
         pure:
            customServiceConfig: |
             [DEFAULT]
             debug = true
             enabled_share_backends=pure-1
             host = hostgroup
             [pure-1]
             driver_handles_share_servers = False
             share_backend_name = pure-1
             share_driver = manila.share.drivers.purestorage.flashblade.FlashBladeShareDriver
             flashblade_mgmt_vip = 203.0.113.15
             flashblade_data_vip = 203.0.10.14
            containerImage: registry.connect.redhat.com/purestorage/openstack-manila-share-pure-rhosp-18-0
            replicas: 1
----

. If providing sensitive information, such as passwords, hostnames and
usernames, it is recommended to use {OpenShift} secrets, and the
`customServiceConfigSecrets` key. An example:
+
[source,yaml]
----
cat << __EOF__ > ~/netapp_secrets.conf

[netapp]
netapp_server_hostname = 203.0.113.10
netapp_login = fancy_netapp_user
netapp_password = secret_netapp_password
netapp_vserver = mydatavserver
__EOF__
----
+
----
oc create secret generic osp-secret-manila-netapp --from-file=~/netapp_secrets.conf -n openstack
----

* `customConfigSecrets` can be used in any service, the following is a
config example using the secret you created above.
+
[source,yaml]
----
  spec:
    manila:
      enabled: true
      template:
        < . . . >
        manilaShares:
         netapp:
           customServiceConfig: |
             [DEFAULT]
             debug = true
             enabled_share_backends = netapp
             host = hostgroup
             [netapp]
             driver_handles_share_servers = False
             share_backend_name = netapp
             share_driver = manila.share.drivers.netapp.common.NetAppDriver
             netapp_storage_family = ontap_cluster
             netapp_transport_type = http
           customServiceConfigSecrets:
             - osp-secret-manila-netapp
           replicas: 1
    < . . . >
----
+
* If you need to present extra files to any of the services, you can use
`extraMounts`. For example, when using ceph, you'd need the {rhos_component_storage_file} ceph
user's keyring file as well as the `ceph.conf` configuration file
available. These are mounted via `extraMounts` as done with the example
below.
* Ensure that the names of the backends (`share_backend_name`) remain as they
did on {OpenStackShort} {rhos_prev_ver}.
* It is recommended to set the replica count of the `manilaAPI` service and
the `manilaScheduler` service to 3. You should ensure to set the replica
count of the `manilaShares` service/s to 1.
* Ensure that the appropriate storage management network is specified in the
`manilaShares` section. The example below connects the `manilaShares`
instance with the CephFS backend driver to the `storage` network.
* Prior to adopting the `manilaShares` service for CephFS through NFS, ensure that
you have a clustered Ceph NFS service created. You will need to provide the
name of the service as ``cephfs_nfs_cluster_id``.

. Patch `OpenStackControlPlane` to deploy the {rhos_component_storage_file}; here's an example that uses
Native CephFS:
+
[source,yaml]
----
cat << __EOF__ > ~/manila.patch
spec:
  manila:
    enabled: true
    apiOverride:
      route: {}
    template:
      databaseInstance: openstack
      databaseAccount: manila
      secret: osp-secret
      manilaAPI:
        replicas: 3
        customServiceConfig: |
          [DEFAULT]
          enabled_share_protocols = cephfs
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
      manilaScheduler:
        replicas: 3
      manilaShares:
        cephfs:
          replicas: 1
          customServiceConfig: |
            [DEFAULT]
            enabled_share_backends = tripleo_ceph
            host = hostgroup
            [cephfs]
            driver_handles_share_servers=False
            share_backend_name=cephfs
            share_driver=manila.share.drivers.cephfs.driver.CephFSDriver
            cephfs_conf_path=/etc/ceph/ceph.conf
            cephfs_auth_id=openstack
            cephfs_cluster_name=ceph
            cephfs_volume_mode=0755
            cephfs_protocol_helper_type=CEPHFS
          networkAttachments:
              - storage
__EOF__
----
+
Below is an example that uses CephFS through NFS. In this example:

* The `cephfs_ganesha_server_ip` option is preserved from the configuration on
the old {OpenStackShort} {rhos_prev_ver} environment.
* The `cephfs_nfs_cluster_id` option is set with the name of the NFS cluster
created on Ceph.
+
[source,yaml]
----
cat << __EOF__ > ~/manila.patch
spec:
  manila:
    enabled: true
    apiOverride:
      route: {}
    template:
      databaseInstance: openstack
      secret: osp-secret
      manilaAPI:
        replicas: 3
        customServiceConfig: |
          [DEFAULT]
          enabled_share_protocols = cephfs
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
      manilaScheduler:
        replicas: 3
      manilaShares:
        cephfs:
          replicas: 1
          customServiceConfig: |
            [DEFAULT]
            enabled_share_backends = cephfs
            host = hostgroup
            [cephfs]
            driver_handles_share_servers=False
            share_backend_name=tripleo_ceph
            share_driver=manila.share.drivers.cephfs.driver.CephFSDriver
            cephfs_conf_path=/etc/ceph/ceph.conf
            cephfs_auth_id=openstack
            cephfs_cluster_name=ceph
            cephfs_protocol_helper_type=NFS
            cephfs_nfs_cluster_id=cephfs
            cephfs_ganesha_server_ip=172.17.5.47
          networkAttachments:
              - storage
__EOF__
----
+
----
oc patch openstackcontrolplane openstack --type=merge --patch-file=~/manila.patch
----

.Verification

. Inspect the resulting {rhos_component_storage_file} pods:
+
----
oc get pods -l service=manila
----

. Check that the {rhos_component_storage_file} API service is registered in {identity_service_first_ref}:
+
----
openstack service list | grep manila
----
+
----
openstack endpoint list | grep manila

| 1164c70045d34b959e889846f9959c0e | regionOne | manila       | share        | True    | internal  | http://manila-internal.openstack.svc:8786/v1/%(project_id)s        |
| 63e89296522d4b28a9af56586641590c | regionOne | manilav2     | sharev2      | True    | public    | https://manila-public-openstack.apps-crc.testing/v2                |
| af36c57adcdf4d50b10f484b616764cc | regionOne | manila       | share        | True    | public    | https://manila-public-openstack.apps-crc.testing/v1/%(project_id)s |
| d655b4390d7544a29ce4ea356cc2b547 | regionOne | manilav2     | sharev2      | True    | internal  | http://manila-internal.openstack.svc:8786/v2                       |
----

. Test the health of the service:
+
----
openstack share service list
openstack share pool list --detail
----

. Check on existing workloads:
+
----
openstack share list
openstack share snapshot list
----

. You can create further resources:
+
----
openstack share create cephfs 10 --snapshot mysharesnap --name myshareclone
openstack share create nfs 10 --name mynfsshare
openstack share export location list mynfsshare
----
