[id="adopting-the-identity-service_{context}"]

= Adopting the {identity_service}

.Prerequisites

* Previous Adoption steps completed. Notably,
 the xref:migrating-databases-to-mariadb-instances_migrating-databases[Migrating databases to MariaDB instances]
must already be imported into the control plane MariaDB.
* Ensure that you copy the fernet keys. Create the `keystone` secret, containing fernet keys:
+
----
oc apply -f - <<EOF
apiVersion: v1
data:
  CredentialKeys0: $($CONTROLLER1_SSH sudo cat /var/lib/config-data/puppet-generated/keystone/etc/keystone/credential-keys/0 | base64 -w 0)
  CredentialKeys1: $($CONTROLLER1_SSH sudo cat /var/lib/config-data/puppet-generated/keystone/etc/keystone/credential-keys/1 | base64 -w 0)
  FernetKeys0: $($CONTROLLER1_SSH sudo cat /var/lib/config-data/puppet-generated/keystone/etc/keystone/fernet-keys/0 | base64 -w 0)
  FernetKeys1: $($CONTROLLER1_SSH sudo cat /var/lib/config-data/puppet-generated/keystone/etc/keystone/fernet-keys/1 | base64 -w 0)
kind: Secret
metadata:
  name: keystone
  namespace: openstack
type: Opaque
EOF
----

.Variables

No shell variables are necessary currently.

.Procedure

. Patch `OpenStackControlPlane` to deploy {identity_service}:
+
----
oc patch openstackcontrolplane openstack --type=merge --patch '
spec:
  keystone:
    enabled: true
    apiOverride:
      route: {}
    template:
      override:
        service:
          internal:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/allow-shared-ip: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.80
            spec:
              type: LoadBalancer
      databaseInstance: openstack
      secret: osp-secret
'
----

. Create an alias to use `openstack` command in the adopted deployment:
+
----
$ alias openstack="oc exec -t openstackclient -- openstack"
----

. Clean up old services and endpoints that still point to the old
control plane, excluding the {identity_service} and its endpoints:
+
----
$ openstack endpoint list | grep keystone | awk '/admin/{ print $2; }' | xargs ${BASH_ALIASES[openstack]} endpoint delete || true

for service in aodh heat heat-cfn barbican cinderv3 glance manila manilav2 neutron nova placement swift ironic-inspector ironic; do
  openstack service list | awk "/ $service /{ print \$2; }" | xargs ${BASH_ALIASES[openstack]} service delete || true
done
----

.Verification

* See that {identity_service} endpoints are defined and pointing to the control plane FQDNs:
+
----
$ openstack endpoint list | grep keystone
----
