[id="configuring-data-plane-nodes_{context}"]

= Configuring isolated networks on data plane nodes

Data plane nodes are configured by `openstack-operator` and its CRs. The CRs define your desired network configuration for the nodes.

Your network configuration should reflect the existing network setup. You must pull the `net_config.yaml` files from each node and reuse them when you define the `OpenStackDataPlaneNodeSet` custom resources (CRs). The format of the configuration has not changed (`os-net-config` is still being used under the hood), so you can put network templates under `edpm_network_config_template` variables, either for all nodes or per node.

To ensure that the latest network configuration is used during the data plane adoption, you should also set `edpm_network_config_update: true` in the `nodeTemplate` attribute of the `OpenStackDataPlaneNodeSet` CR.

You proceed with the data plane adoption after the {OpenShiftShort} control plane is deployed in the {OpenShiftShort} cluster. When doing so, you configure `NetConfig` and `OpenStackDataPlaneNodeSet` CRs, using the same VLAN tags and IPAM configuration as determined in the previous steps.

.Procedure

. Configure a `NetConfig` CR with your desired VLAN tags and IPAM configuration. For example:
+
----
apiVersion: network.openstack.org/v1beta1
kind: NetConfig
metadata:
  name: netconfig
spec:
  networks:
  - name: internalapi
    dnsDomain: internalapi.example.com
    subnets:
    - name: subnet1
      allocationRanges:
      - end: 172.17.0.250
        start: 172.17.0.100
      cidr: 172.17.0.0/24
      vlan: 20
  - name: storage
    dnsDomain: storage.example.com
    subnets:
    - name: subnet1
      allocationRanges:
      - end: 172.18.0.250
        start: 172.18.0.100
      cidr: 172.18.0.0/24
      vlan: 21
  - name: tenant
    dnsDomain: tenant.example.com
    subnets:
    - name: subnet1
      allocationRanges:
      - end: 172.19.0.250
        start: 172.19.0.100
      cidr: 172.19.0.0/24
      vlan: 22
----

. Optional: In the `NetConfig` CR, list multiple `allocationRanges` entries to exclude some of the IP addresses, for example, to accommodate for IP addresses already consumed by the adopted environment:
+
----
apiVersion: network.openstack.org/v1beta1
kind: NetConfig
metadata:
  name: netconfig
spec:
  networks:
  - name: internalapi
    dnsDomain: internalapi.example.com
    subnets:
    - name: subnet1
      allocationRanges:
      - end: 172.17.0.199
        start: 172.17.0.100
      - end: 172.17.0.250
        start: 172.17.0.201
      cidr: 172.17.0.0/24
      vlan: 20
----
+
This example excludes the `172.17.0.200` address from the pool.
