[id="stopping-infrastructure-management-and-compute-services_{context}"]

= Stopping infrastructure management and Compute services

You must decomission cloud Controller nodes, database nodes, and messaging nodes on the source cloud's control plane. Nodes that are running the Compute, Storage, or Networker roles must remain functional (in terms of composable roles covered by {OpenStackPreviousInstaller} Heat Templates).

The following procedure applies to a single node standalone {OpenStackPreviousInstaller} deployment. You must remove conflicting repositories and packages from your Compute hosts. That is required to install libvirt packages when these hosts are adopted as data plane nodes, where modular libvirt daemons are no longer running in podman containers.

.Prerequisites

* Define the following shell variables. Replace the following example values with values that are correct for your environment:
+
[subs=+quotes]
----
ifeval::["{build}" != "downstream"]
EDPM_PRIVATEKEY_PATH="~/install_yamls/out/edpm/ansibleee-ssh-key-id_rsa"
endif::[]
ifeval::["{build}" == "downstream"]
EDPM_PRIVATEKEY_PATH="<path_to_SSH_key>"
endif::[]
declare -A computes
computes=(
  ["standalone.localdomain"]="192.168.122.100"
  # ...
)
----
+
** Replace `["standalone.localdomain"]="192.168.122.100"` with the name of the Compute node and its IP address.
** Replace `<path_to_SSH_key>` with the path to your SSH key.
+
[NOTE]
====
These ssh variables with the ssh commands are used instead of ansible to create instructions that are independent of where they are running. But ansible commands could be used to achieve the same result if you are in the right host, for example to stop a service, run the following command:

----
. stackrc
ansible -i $(which tripleo-ansible-inventory) Compute -m shell -a "sudo systemctl stop tripleo_virtqemud.service" -b
----
====

.Procedure

* Remove the conflicting repositories and packages from all Compute hosts:
+
----
PacemakerResourcesToStop=(
                "galera-bundle"
                "haproxy-bundle"
                "rabbitmq-bundle")

echo "Stopping pacemaker services"
for i in {1..3}; do
    SSH_CMD=CONTROLLER${i}_SSH
    if [ ! -z "${!SSH_CMD}" ]; then
        echo "Using controller $i to run pacemaker commands"
        for resource in ${PacemakerResourcesToStop[*]}; do
            if ${!SSH_CMD} sudo pcs resource config $resource; then
                ${!SSH_CMD} sudo pcs resource disable $resource
            fi
        done
        break
    fi
done
----
