[id="adopting-telemetry-services_{context}"]

= Adopting Telemetry services

Adopting Telemetry means that an existing `OpenStackControlPlane` custom resource (CR), where Telemetry services are supposed to be disabled, should be patched to start the service with the configuration parameters provided by the source environment.

This guide also assumes that:

. A `TripleO` environment (the source Cloud) is running on one side;
. A `SNO` / `CodeReadyContainers` is running on the other side.

.Prerequisites

* Previous Adoption steps completed. MariaDB, the {identity_service_first_ref} and the data plane should be already adopted. 
//kgilliga:Should this procedure be moved after the "Adopting the data plane" chapter?

.Procedure

. Patch the `OpenStackControlPlane` CR to deploy Ceilometer services:
// TODO(jistr): There are still some quay.io images in the downstream build.
+
----
cat << EOF > ceilometer_patch.yaml
spec:
  ceilometer:
    enabled: true
    template:
ifeval::["{build}" != "downstream"]
      centralImage: quay.io/podified-antelope-centos9/openstack-ceilometer-central:current-podified
      computeImage: quay.io/podified-antelope-centos9/openstack-ceilometer-compute:current-podified
      customServiceConfig: |
        [DEFAULT]
        debug=true
      ipmiImage: quay.io/podified-antelope-centos9/openstack-ceilometer-ipmi:current-podified
      nodeExporterImage: quay.io/prometheus/node-exporter:v1.5.0
      notificationImage: quay.io/podified-antelope-centos9/openstack-ceilometer-notification:current-podified
      secret: osp-secret
      sgCoreImage: quay.io/infrawatch/sg-core:v5.1.1
endif::[]
ifeval::["{build}" == "downstream"]
      centralImage: registry.redhat.io/rhosp-dev-preview/openstack-ceilometer-central-rhel9:18.0
      computeImage: registry.redhat.io/rhosp-dev-preview/openstack-ceilometer-compute-rhel9:18.0
      customServiceConfig: |
        [DEFAULT]
        debug=true
      ipmiImage: registry.redhat.io/rhosp-dev-preview/openstack-ceilometer-ipmi-rhel9:18.0
      nodeExporterImage: quay.io/prometheus/node-exporter:v1.5.0
      notificationImage: registry.redhat.io/rhosp-dev-preview/openstack-ceilometer-notification-rhel9:18.0
      secret: osp-secret
      sgCoreImage: quay.io/infrawatch/sg-core:v5.1.1
endif::[]
EOF
----

. Optional: If you previously backed up your {OpenStackShort} services configuration file from the old environment, you can use os-diff to compare and make sure the configuration is correct. This will produce the difference between both ini configuration files:
+
----
pushd os-diff
./os-diff cdiff --service ceilometer -c /tmp/collect_tripleo_configs/ceilometer/etc/ceilometer/ceilometer.conf -o ceilometer_patch.yaml
----
+
For more information, see xref:pulling-the-openstack-configuration_{context}[Reviewing the {rhos_prev_long} control plane configuration].

. Patch the `OpenStackControlPlane` CR to deploy Ceilometer services:
+
----
oc patch openstackcontrolplane openstack --type=merge --patch-file ceilometer_patch.yaml
----

.Verification

. Inspect the resulting Ceilometer pods:
+
----
CEILOMETETR_POD=`oc get pods -l service=ceilometer | tail -n 1 | cut -f 1 -d' '`
oc exec -t $CEILOMETETR_POD -c ceilometer-central-agent -- cat /etc/ceilometer/ceilometer.conf
----

. Inspect the resulting Ceilometer IPMI agent pod on data plane nodes:
+
----
podman ps | grep ceilometer-ipmi
----

. Inspect enabled pollsters:
+
----
oc get secret ceilometer-config-data -o jsonpath="{.data['polling\.yaml']}"  | base64 -d
----

. Enable pollsters according to requirements:
+
----
cat << EOF > polling.yaml
---
sources:
    - name: pollsters
      interval: 300
      meters:
        - volume.size
        - image.size
        - cpu
        - memory
EOF

oc patch secret ceilometer-config-data  --patch="{\"data\": { \"polling.yaml\": \"$(base64 -w0 polling.yaml)\"}}"
----
