[id="adopting-autoscaling_{context}"]

= Adopting Autoscaling

Adopting autoscaling means that an existing `OpenStackControlPlane` custom resource (CR), where Aodh services are supposed to be disabled, should be patched to start the service with the configuration parameters provided by the source environment.

This guide also assumes that:

. A {OpenStackPreviousInstaller} environment (the source Cloud) is running on one side;
. A `SNO` / `CodeReadyContainers` is running on the other side.

.Prerequisites

* Previous Adoption steps completed. MariaDB, the {identity_service_first_ref}, the {orchestration_first_ref}, and Telemetry
should be already adopted.
//kgilliga: Should this procedure be moved to after the data plane adoption chapter?

.Procedure

. Patch the `OpenStackControlPlane` CR to deploy autoscaling services:
+
----
oc patch openstackcontrolplane openstack --type=merge --patch '
spec:
  telemetry:
    template:
      autoscaling:
        aodh:
          databaseAccount: aodh
          databaseInstance: openstack
          passwordSelector:
            aodhService: AodhPassword
            ceilometerService: CeilometerPassword
          preserveJobs: false
          rabbitMqClusterName: rabbitmq
          secret: osp-secret
          serviceUser: aodh
        enabled: true
        heatInstance: heat
EOF
----

. Optional: If you have previously backed up your {OpenStackShort} services configuration file from the old environment, you can use os-diff to compare and make sure the configuration is correct. This will producre the difference between both ini configuration files:
+
----
os-diff diff /tmp/collect_tripleo_configs/aodh/etc/aodh/aodh.conf aodh_patch.yaml --crd
----
+
For more information, see xref:reviewing-the-openstack-control-plane-configuration_{context}[Reviewing the {rhos_prev_long} control plane configuration].

. Patch the `OpenStackControlPlane` CR to deploy cluster-observability-operator:
+
----
oc create -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-observability-operator
  namespace: openshift-operators
spec:
  channel: development
  installPlanApproval: Automatic
  name: cluster-observability-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
EOF
----

. Wait for the installation to succeed
+
----
oc wait --for jsonpath="{.status.phase}"=Succeeded csv --namespace=openshift-operators -l operators.coreos.com/cluster-observability-operator.openshift-operators
----

. Enable metrics storage backend
+
----
oc patch openstackcontrolplane openstack-galera-network-isolation --type=merge --patch '
spec:
  telemetry:
    template:
      metricStorage:
        enabled: true
'
----

.Verification

. If autoscaling services are enabled, inspect Aodh pods:
+
----
AODH_POD=`oc get pods -l service=aodh | tail -n 1 | cut -f 1 -d' '`
oc exec -t $AODH_POD -c aodh-api -- cat /etc/aodh/aodh.conf
----

. Check whether Aodh API service is registered in {identity_service}:
+
----
openstack endpoint list | grep aodh
| d05d120153cd4f9b8310ac396b572926 | regionOne | aodh  | alarming  | True    | internal  | http://aodh-internal.openstack.svc:8042  |
| d6daee0183494d7a9a5faee681c79046 | regionOne | aodh  | alarming  | True    | public    | http://aodh-public.openstack.svc:8042    |
----

. Create sample resources. You can test whether you can create alarms:
+
----
oc get pods -l alertmanager=metric-storage
NAME                            READY   STATUS    RESTARTS   AGE
alertmanager-metric-storage-0   2/2     Running   0          17h
alertmanager-metric-storage-1   2/2     Running   0          17h

oc get pods -l prometheus=metric-storage
NAME                          READY   STATUS    RESTARTS   AGE
prometheus-metric-storage-0   3/3     Running   0          17h
----

.Autoscaling template adoption

* `PrometheusAlarm` alarm type must be used instead of `GnocchiAggregationByResourcesAlarm`

//=== (TODO)

//* Include adopted Aodh alarm create commands of type prometheus
