[id="adopting-the-compute-service_{context}"]

= Adopting the {compute_service}

[NOTE]
This example scenario describes a simple single-cell setup. Real
multi-stack topology recommended for production use results in different
cells DBs layout, and should be using different naming schemes (not covered
here this time).

.Prerequisites

* Previous Adoption steps completed. Notably,
 ** the xref:migrating-databases-to-mariadb-instances_migrating-databases[Migrating databases to MariaDB instances]
must already be imported into the control plane MariaDB;
 ** the xref:adopting-the-identity-service_adopt-control-plane[Adopting the Identity service] needs to be imported;
 ** the xref:adopting-the-key-manager-service_adopt-control-plane[Adopting the Key Manager service] needs to be imported;
 ** the xref:adopting-the-placement-service_{context}[Adopting the Placement service] needs to be imported;
 ** the xref:adopting-the-image-service_adopt-control-plane[Adopting the Image service] needs to be imported;
 ** the xref:migrating-ovn-data_migrating-databases[Migrating OVN data] need to be imported;
 ** the xref:adopting-the-networking-service_adopt-control-plane[Adopting the Networking service] needs to be imported;
** the {bare_metal} needs to be imported; 
//kgilliga:I removed the link because it did not work. I might rewrite this section anyway.
 ** Required services specific topology
xref:proc_retrieving-services-topology-specific-configuration_adopt-control-plane[Retrieving services from a topology specific-configuration].
 ** {rhos_prev_long} services have been stopped. For more information, see xref:stopping-openstack-services_migrating-databases[Stopping {rhos_prev_long} services].
* Define the following shell variables. The values that are used are examples. Replace these example values with values that are correct for your environment:
----
alias openstack="oc exec -t openstackclient -- openstack"
----

.Procedure

[NOTE]
This procedure assumes that {compute_service} Metadata is deployed on the top level and not on each cell level, so this example imports it the same way. If the source deployment has a per cell metadata deployment, adjust the given below patch as needed. Metadata service cannot be run in `cell0`.


. Patch `OpenStackControlPlane` to deploy the {compute_service}:
+
[source,yaml]
----
oc patch openstackcontrolplane openstack -n openstack --type=merge --patch '
spec:
  nova:
    enabled: true
    apiOverride:
      route: {}
    template:
      secret: osp-secret
      apiServiceTemplate:
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
        customServiceConfig: |
          [workarounds]
          disable_compute_service_check_for_ffu=true
      metadataServiceTemplate:
        enabled: true # deploy single nova metadata on the top level
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/allow-shared-ip: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.80
            spec:
              type: LoadBalancer
        customServiceConfig: |
          [workarounds]
          disable_compute_service_check_for_ffu=true
      schedulerServiceTemplate:
        customServiceConfig: |
          [workarounds]
          disable_compute_service_check_for_ffu=true
      cellTemplates:
        cell0:
          conductorServiceTemplate:
            customServiceConfig: |
              [workarounds]
              disable_compute_service_check_for_ffu=true
        cell1:
          metadataServiceTemplate:
            enabled: false # enable here to run it in a cell instead
            override:
                service:
                  metadata:
                    annotations:
                      metallb.universe.tf/address-pool: internalapi
                      metallb.universe.tf/allow-shared-ip: internalapi
                      metallb.universe.tf/loadBalancerIPs: 172.17.0.80
                  spec:
                    type: LoadBalancer
            customServiceConfig: |
              [workarounds]
              disable_compute_service_check_for_ffu=true
          conductorServiceTemplate:
            customServiceConfig: |
              [workarounds]
              disable_compute_service_check_for_ffu=true
'
----

* If adopting {compute_service_first_ref} with the Baremetal service (`ironic`), append the following `novaComputeTemplates` in the `cell1` section of the {compute_service} CR patch:
+
*NOTE*: Set the `[DEFAULT]host` configuration option to match the hostname of the node running the `ironic` compute driver in the source cloud.
+
[source,yaml]
----
        cell1:
          novaComputeTemplates:
            standalone:
              customServiceConfig: |
                [DEFAULT]
                host = standalone.localdomain
                [workarounds]
                disable_compute_service_check_for_ffu=true
----

. Wait for {compute_service} control plane services' custom resources (CRs) to become ready:
+
----
oc wait --for condition=Ready --timeout=300s Nova/nova
----
+
The local Conductor services will be started for each cell, while the superconductor runs in `cell0`.
Note that `disable_compute_service_check_for_ffu` is mandatory for all imported Nova services, until the external data plane is imported, and until Nova Compute services fast-forward upgraded. For more information, see xref:adopting-compute-services-to-the-data-plane_data-plane[Adopting Compute services to the {rhos_acro} data plane] and xref:performing-a-fast-forward-upgrade-on-compute-services_data-plane[Performing a fast-forward upgrade on Compute services].

.Verification 

* Check that {compute_service} endpoints are defined and pointing to the
control plane FQDNs and that Nova API responds.
+
----
$ openstack endpoint list | grep nova
$ openstack server list
----

Compare the following outputs with the topology specific configuration in xref:proc_retrieving-services-topology-specific-configuration_{context}[Retrieving services from a topology specific-configuration].

* Query the superconductor for cell1 existance and compare it to pre-adoption values:
+
----
. ~/.source_cloud_exported_variables
echo $PULL_OPENSTACK_CONFIGURATION_NOVAMANAGE_CELL_MAPPINGS
oc rsh nova-cell0-conductor-0 nova-manage cell_v2 list_cells | grep -F '| cell1 |'
----
+
The expected changes to happen:

 ** cell1's `nova` DB and user name become `nova_cell1`.
 ** Default cell is renamed to `cell1` (in a multi-cell setup, it should become indexed as the last cell instead).
 ** RabbitMQ transport URL no longer uses `guest`.

[NOTE]
At this point, the {compute_service} control plane services do not control the existing {compute_service} Compute workloads. The control plane manages the data plane only after the data adoption process is successfully completed. For more information, see xref:adopting-compute-services-to-the-data-plane_data-plane[Adopting Compute services to the {rhos_acro} data plane].
