[id="adopting-telemetry-services_{context}"]

= Adopting Telemetry services

The observability solution that is used in  the source environment (STF) is not the observability solution used to retrieve metrics and logs in the target environment. It has been developed with a better integration with both OpenStack and OpenShift. This means that different backends are used, rendering old data not automatically migrable.

Metrics and logs are considered short-lived data and thus they are not intended to be migrated to the target environment. A procedure to adopt legacy autoscaling stack templates to the target environment is provided in the autoscaling documentation.

Adopting Telemetry means that the solution will be removed from the cluster and the new solution will be deployed in the target environment, allowing for metrics (and optionally logs) retrieval and storage in the new backends.

To achieve this an existing `OpenStackControlPlane` custom resource (CR), where Telemetry services are supposed to be disabled, should be patched to start the service with the configuration parameters provided by the source environment.

This guide also assumes that:

. A {OpenStackPreviousInstaller} environment (the source Cloud) is running on one side;
. A `SNO` / `CodeReadyContainers` is running on the other side.

.Prerequisites

* Previous Adoption steps completed. MariaDB, the {identity_service_first_ref} and the data plane should be already adopted.
//kgilliga:Should this procedure be moved after the "Adopting the data plane" chapter?

* Patch the `OpenStackControlPlane` CR to deploy `cluster-observability-operator`:
+
----
oc create -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-observability-operator
  namespace: openshift-operators
spec:
  channel: development
  installPlanApproval: Automatic
  name: cluster-observability-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
EOF
----

* Wait for the installation to succeed
+
----
oc wait --for jsonpath="{.status.phase}"=Succeeded csv --namespace=openshift-operators -l operators.coreos.com/cluster-observability-operator.openshift-operators
----

* Enable metrics storage backend
+
----
oc patch openstackcontrolplane openstack --type=merge --patch '
spec:
  telemetry:
    template:
      metricStorage:
        enabled: true
        monitoringStack:
          alertingEnabled: true
          scrapeInterval: 30s
          storage:
            strategy: persistent
            retention: 24h
            persistent:
              pvcStorageRequest: 20G
'
----

* Verify that `alertmanager` and `prometheus` pods are available
+
----
oc get pods -l alertmanager=metric-storage -n openstack
NAME                            READY   STATUS    RESTARTS   AGE
alertmanager-metric-storage-0   2/2     Running   0          46s
alertmanager-metric-storage-1   2/2     Running   0          46s

oc get pods -l prometheus=metric-storage -n openstack
NAME                          READY   STATUS    RESTARTS   AGE
prometheus-metric-storage-0   3/3     Running   0          46s
----

.Procedure

* Patch the `OpenStackControlPlane` CR to deploy Ceilometer services:
+
----
oc patch openstackcontrolplane openstack --type=merge --patch '
spec:
  telemetry:
    enabled: true
    template:
      ceilometer:
        passwordSelector:
          ceilometerService: CeilometerPassword
        enabled: true
        secret: osp-secret
        serviceUser: ceilometer
'
----

.Verification

. Inspect the resulting Ceilometer pods:
+
----
CEILOMETETR_POD=`oc get pods -l service=ceilometer -n openstack | tail -n 1 | cut -f 1 -d' '`
oc exec -t $CEILOMETETR_POD -c ceilometer-central-agent -- cat /etc/ceilometer/ceilometer.conf
----

. Inspect enabled pollsters:
+
----
oc get secret ceilometer-config-data -o jsonpath="{.data['polling\.yaml\.j2']}"  | base64 -d
----

. Optional: Override default pollsters according to requirements:
+
----
oc patch openstackcontrolplane controlplane --type=merge --patch '
spec:
  telemetry:
    template:
      ceilometer:
          defaultConfigOverwrite:
            polling.yaml.j2: |
              ---
              sources:
                - name: pollsters
                  interval: 100
                  meters:
                    - volume.*
                    - image.size
          enabled: true
          secret: osp-secret
'
----

* Patch the `OpenStackControlPlane` CR to include `logging`
+
----
oc patch openstackcontrolplane openstack --type=merge --patch '
spec:
  telemetry:
    template:
      logging:
      enabled: false
      ipaddr: 172.17.0.80
      port: 10514
      cloNamespace: openshift-logging
'
----
