[id="installing-the-systemd-container-package-on-compute-hosts_{context}"]

= Installing the `systemd-container` package on Compute hosts

Before you adopt the {rhos_long} data plane, you must install the `systemd-container` package on all the hypervisors on your Compute hosts.

.Procedure

. If your Compute hosts are running virtual machines, live migrate them from each host. For more information about live migration, see link:https://docs.redhat.com/en/documentation/red_hat_openstack_platform/17.1/html/performing_a_minor_update_of_red_hat_openstack_platform/assembly_rebooting-the-overcloud_keeping-updated#proc_rebooting-compute-nodes_rebooting-the-overcloud[Rebooting Compute nodes] in _Performing a minor update of Red Hat OpenStack Platform_.

. Install the `systemd-container`:
** If you upgraded your environment from an earlier version of {rhos_prev_long}, reboot each Compute host to automatically install the `systemd-container`.
** If you deployed a new RHOSO environment, install the `systemd-container` manually by using the following command. Rebooting the Compute hosts is not required.
+
----
$ sudo dnf -y install systemd-container
----
[NOTE]
If no virtual machines are running on your Compute hosts, you can install the `systemd-container` automatically or manually.

. Repeat this procedure on each hypervisor one by one.


