[id="using-new-subnet-ranges_{context}"]

= Configuring new subnet ranges

You can define new IP ranges for control plane services that belong to a different subnet that is not used in the existing cluster. Then you configure link local IP routing between the existing and new subnets to enable existing and new service deployments to communicate. This involves using the {OpenStackPreviousInstaller} mechanism on a pre-adopted cluster to configure additional link local routes. This enables the data plane deployment to reach out to {rhos_prev_long} ({OpenStackShort}) nodes by using the existing subnet addresses. You can use new subnet ranges with any existing subnet configuration, and when the existing cluster subnet ranges do not have enough free IP addresses for the new control plane services.

You must size the new subnet appropriately to accommodate the new control
plane services. There are no specific requirements for the
existing deployment allocation pools that are already consumed by the {OpenStackShort} environment.

In the following procedure, you configure `NetworkAttachmentDefinition` custom resources (CRs) to use a different subnet from what is configured in the `NetConfig` CR for the same networks. The former range is used for control plane services, while the new range is used to manage IP Address Management (IPAM) for data plane nodes.

The values that are used in the following procedure are examples. Use values that are specific to your configuration.

[IMPORTANT]
Do not change {OpenStackShort} node IP addresses during the adoption process. List the IP addresses in the `fixedIP` fields for each node entry in the `nodes` section of the `OpenStackDataPlaneNodeSet` CR.

.Procedure

. In the `NetworkAttachmentDefinition` CR, configure host routes on the {OpenStackShort} nodes for the control plane subnets. For example:
+
----
network_config:
  - type: ovs_bridge
    name: br-ctlplane
    routes:
    - ip_netmask: 0.0.0.0/0
      next_hop: 192.168.1.1
    - ip_netmask: 172.31.0.0/24 <1>
      next_hop: 192.168.1.100 <2>
----
<1> The new control plane subnet.
<2> The control plane IP address of the existing data plane node.
+
Repeat this step for other networks that need to use different subnets for the new and existing parts of the deployment.

. Apply the new configuration to every {OpenStackShort} node:
+
----
$ openstack overcloud node provision
--stack <stack>
--network_config
----
+
[NOTE]
Network configuration changes are not applied by default to avoid
the risk of network disruption. You must enforce the changes by setting the
`StandaloneNetworkConfigUpdate: true` in the {OpenStackPreviousInstaller} configuration files.

. Confirm that there are new link local routes to the new subnet on each node. For example:
+
----
# ip route | grep 172
172.31.0.0/24 via 192.168.122.100 dev br-ctlplane
----

. To configure similar routes for the existing subnet for the control plane services that are attached to the networks, add `routes` entries to the `NodeNetworkConfigurationPolicy` CRs for each network. For example:
+
----
      - destination: 192.168.122.0/24 <1>
        next-hop-interface: ospbr <2>
----
<1> The original subnet of the isolated network on the data plane.
<2> The {rhocp_long} worker network interface that corresponds to the isolated network on the data plane.
+
As a result, the following route is added to your {OpenShiftShort} nodes:
+
----
# ip route | grep 192
192.168.122.0/24 dev ospbr proto static scope link
----
+
At this point, you can ping the adopted nodes from the {OpenShiftShort} nodes by using the existing subnet IP addresses.

. During the data plane adoption, in the `network_config` section of the `OpenStackDataPlaneNodeSet` CR, add link local routes to the new subnets. For example:
+
----
  nodeTemplate:
    ansible:
      ansibleUser: root
      ansibleVars:
        additional_ctlplane_host_routes:
        - ip_netmask: 172.31.0.0/24
          next_hop: '{{ ctlplane_ip }}'
        edpm_network_config_template: |
          network_config:
          - type: ovs_bridge
            routes: {{ ctlplane_host_routes + additional_ctlplane_host_routes }}
            ...
----

. List the previous IP addresses as `ansibleHost` and `fixedIP`. For example:
+
----
  nodes:
    standalone:
      ansible:
        ansibleHost: 192.168.122.100
        ansibleUser: ""
      hostName: standalone
      networks:
      - defaultRoute: true
        fixedIP: 192.168.122.100
        name: ctlplane
        subnetName: subnet1
----

. Expand the SSH range for the firewall configuration to include both subnets:
+
----
        edpm_sshd_allowed_ranges:
        - 192.168.122.0/24
        - 172.31.0.0/24
----
+
This provides SSH access from the new subnet to the {OpenStackShort} nodes as well as the {OpenStackShort} subnets.

. Optional: Set `edpm_network_config_update: true` to enforce the changes that you are applying to the nodes:

