[id="migrating-tls-everywhere_{context}"]

//:context: tls

= Migrating TLS-e to the {rhos_acro} deployment

The {rhos_long} deployment adopts the settings from the
{rhos_prev_long} ({OpenStackShort}) {rhos_prev_ver}  deployment. If TLS everywhere (TLS-e) is disabled in the {OpenStackShort} deployment, it is not enabled in the {rhos_acro} deployment.

If the {OpenStackPreviousInstaller} deployment was deployed with TLS-e, FreeIPA (IdM) is used to issue certificates for the {OpenStackShort} services. Certmonger, a client process which is installed on all hosts, interacts with FreeIPA (IdM) to request, install, track and renew these certificates.

The {rhos_acro} Operator-based deployment uses the cert-manager operator to issue, track, and renew the certificates.

Because the same root certificate authority (CA) is used to generate new certificates, you do not have to modify the currently used chain of trust.
_Disclaimer: the below steps were reproduced on a FreeIPA 4.10.1 server. The location of files and directories may slightly change on different versions._

These instructions explain how to extract the CA signing certificate from the FreeIPA instance that is used to provide the certificates in the source environment and import it into certmanager for use in the target environment. In this way, disruption on the Compute nodes can be minimized because a new chain of trust need not be installed.

It is expected that the old FreeIPA node is then decommissioned and no longer used to issue certificates. This might not be possible if the IPA server is used to issue certificates for non-{OpenStackShort} systems.

This procedure will also need to be modified if the signing keys are stored in an hardware security module (HSM) instead of an NSS shared database (NSSDB). In that case, if the key is retrievable, special HSM utilities might be required.
//kgilliga: Note to self: This intro will need to be rewritten/reorganized. Determine the most relevant info.

.Prerequisites

* Your {OpenStackShort} deployment is using TLS-e.
* Make sure the previous Adoption steps (if any) have been performed successfully.
* Make sure the backend services on the new deployment are not started yet.
* Define the following shell variables. The values that are used are examples and refer to a single node standalone {OpenStackPreviousInstaller} deployment. Replace these example values with values that are correct for your environment:
+
ifeval::["{build}" != "downstream"]
----
IPA_SSH="ssh -i ~/install_yamls/out/edpm/ansibleee-ssh-key-id_rsa root@192.168.122.100 podman exec -ti freeipa-server-container"
----
+
In this example the FreeIPA instance is running on a separate host, in a container.
endif::[]
ifeval::["{build}" == "downstream"]
----
IPA_SSH="ssh -i <path_to_ssh_key> root@<freeipa-server-ip-address>"
----
endif::[]

* Define the map of Compute node name, IP pairs.
//kgilliga: Is this a separate prerequisite or is this part of "defining shell variables"?
+
[subs=+quotes]
----
ifeval::["{build}" != "downstream"]
EDPM_PRIVATEKEY_PATH="~/install_yamls/out/edpm/ansibleee-ssh-key-id_rsa"
endif::[]
ifeval::["{build}" == "downstream"]
EDPM_PRIVATEKEY_PATH="*<path to SSH key>*"
endif::[]
declare -A computes
computes=(
  ["standalone.localdomain"]="192.168.122.100"
  # ...
)
----

.Procedure

. To locate the CA certificate and key, list all the certificates inside your NSSDB:
+
----
$IPA_SSH certutil -L -d /etc/pki/pki-tomcat/alias
----
+
The `-L` option lists all certificates, and `-d` specifies where they are stored. This will produce some output like this:
+
----
Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

caSigningCert cert-pki-ca                                    CTu,Cu,Cu
ocspSigningCert cert-pki-ca                                  u,u,u
Server-Cert cert-pki-ca                                      u,u,u
subsystemCert cert-pki-ca                                    u,u,u
auditSigningCert cert-pki-ca                                 u,u,Pu
----
+
The item you need to consider is the first one: `caSigningCert cert-pki-ca`.


. Export the certificate and key from the `/etc/pki/pki-tomcat/alias` directory:
+
----
$IPA_SSH pk12util -o /tmp/freeipa.p12 -n 'caSigningCert\ cert-pki-ca' -d /etc/pki/pki-tomcat/alias -k /etc/pki/pki-tomcat/alias/pwdfile.txt -w /etc/pki/pki-tomcat/alias/pwdfile.txt
----
+
The command generates a P12 file with both the certificate and the key. The `/etc/pki/pki-tomcat/alias/pwdfile.txt` file contains the password that protects the key. You can use it to both extract the key and generate the new file, `/tmp/freeipa.p12`. You can also choose another password. If you choose to apply a different password for the new file, replace the parameter of the `-w` option, or use the `-W` (capital W) option followed by the password (in clear text).
+
With that file, you can also separately get the certificate and the key by using the `openssl pkcs12` command.

. Create the secret that contains the root CA:
+
----
oc create secret generic rootca-internal -n openstack
----

. Import the certificate and the key from FreeIPA:
+
----
oc patch secret rootca-internal -n openstack -p="{\"data\":{\"ca.crt\": \"`$IPA_SSH openssl pkcs12 -in /tmp/freeipa.p12 -passin file:/etc/pki/pki-tomcat/alias/pwdfile.txt -nokeys | openssl x509 | base64 -w 0`\"}}"

oc patch secret rootca-internal -n openstack -p="{\"data\":{\"tls.crt\": \"`$IPA_SSH openssl pkcs12 -in /tmp/freeipa.p12 -passin file:/etc/pki/pki-tomcat/alias/pwdfile.txt -nokeys | openssl x509 | base64 -w 0`\"}}"

oc patch secret rootca-internal -n openstack -p="{\"data\":{\"tls.key\": \"`$IPA_SSH openssl pkcs12 -in /tmp/freeipa.p12 -passin file:/etc/pki/pki-tomcat/alias/pwdfile.txt -nocerts -noenc | openssl rsa | base64 -w 0`\"}}"
----

. Create the cert-manager Issuer and reference the created secret:
+
[source, yaml]
----
oc apply -f - <<EOF
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: rootca-internal
  namespace: openstack
  labels:
    osp-rootca-issuer-public: ""
    osp-rootca-issuer-internal: ""
    osp-rootca-issuer-libvirt: ""
    osp-rootca-issuer-ovn: ""
spec:
  ca:
    secretName: rootca-internal
EOF
----

. Delete the previously created p12 files:
+
----
$IPA_SSH rm /tmp/freeipa.p12
----


. Verify that the necessary resources were created by using the following commands:
+
----
oc get issuers -n openstack
----
+
----
oc get secret rootca-internal -n openstack -o yaml
----

. Stop and disable the certmonger service on all data plane nodes, and stop tracking all certificates managed by the service:
+
----
#!/bin/bash

for i in "${!computes[@]}"; do
    SSH_CMD="ssh -i $EDPM_PRIVATEKEY_PATH root@${computes[$i]}"
    if ${SSH_CMD} sudo systemctl is-active certmonger.service; then
        echo "Stopping certmonger on $i..."
        ${SSH_CMD} sudo systemctl stop certmonger.service
        echo "Disabling certmonger on $i..."
        ${SSH_CMD} sudo systemctl disable --now certmonger.service
        ${SSH_CMD} test -f /etc/systemd/system/certmonger.service '||' sudo systemctl mask certmonger.service
    fi
    # If necessary, adjust the directory below accordingly.
    certs_directory=/var/lib/certmonger/requests
    certs_to_stop=$(${SSH_CMD} ls -1 $certs_directory)
    number_of_certs=$(${SSH_CMD} ls -1 $certs_directory | wc -l)
    if [ $? != 0 ] || [ $number_of_certs = 0 ]; then
        echo "No certificates to stop tracking on $i."
    else
        echo "There is/are $number_of_certs certificates to stop being tracked on $i. Stopping to track certificates..."
    fi

    for cert in $certs_to_stop; do
        echo "Stopping to track $cert..."
        ${SSH_CMD} rm -f $certs_directory/$cert
    done

done
----

[NOTE]
After the adoption procedure is finished, the cert-manager operator is responsible for issuing and refreshing new certificates when they expire.
However, since Compute services are not restarted during adoption, you need to restart the data plane (Compute) nodes before the certificates expire. Check the expiration dates of all certificates and plan accordingly.
