[id="stopping-infrastructure-management-and-compute-services_{context}"]

= Stopping infrastructure management and Compute services

The source cloud's control plane can be decomissioned,
which is taking down only cloud controllers, database and messaging nodes.
Nodes that must remain functional are those running the Compute, storage,
or networker roles (in terms of composable roles covered by Tripleo Heat
Templates).

.Variables

Define the following shell variables.
Define the map of Compute node name, IP pairs.
The values are just illustrative and refer to a single node standalone {OpenStackPreviousInstaller} deployment, use values that are correct for your environment: 
//kgilliga: Is this correct? Standalone director deployment for downstream, standalone tripleo for upstream?

[subs=+quotes]
----
ifeval::["{build}" != "downstream"]
EDPM_PRIVATEKEY_PATH="~/install_yamls/out/edpm/ansibleee-ssh-key-id_rsa"
endif::[]
ifeval::["{build}" == "downstream"]
EDPM_PRIVATEKEY_PATH="*<path to SSH key>*"
endif::[]
declare -A computes
computes=(
  ["standalone.localdomain"]="192.168.122.100"
  # ...
)
----

These ssh variables with the ssh commands are used instead of ansible to try to create instructions that are independent on where they are running. But ansible commands could be used to achieve the same result if you are in the right host, for example to stop a service:

----
. stackrc
ansible -i $(which tripleo-ansible-inventory) Compute -m shell -a "sudo systemctl stop tripleo_virtqemud.service" -b
----

.Procedure

* Run the following script to remove the conflicting repositories and packages (in case of a devsetup that uses Standalone {OpenStackPreviousInstaller}) from all Compute hosts. That is required to install libvirt packages, when these hosts become adopted as data plane nodes, where modular libvirt daemons are no longer running in podman containers:
+
----

PacemakerResourcesToStop=(
                "galera-bundle"
                "haproxy-bundle"
                "rabbitmq-bundle")

echo "Stopping pacemaker services"
for i in {1..3}; do
    SSH_CMD=CONTROLLER${i}_SSH
    if [ ! -z "${!SSH_CMD}" ]; then
        echo "Using controller $i to run pacemaker commands"
        for resource in ${PacemakerResourcesToStop[*]}; do
            if ${!SSH_CMD} sudo pcs resource config $resource; then
                ${!SSH_CMD} sudo pcs resource disable $resource
            fi
        done
        break
    fi
done
----
