[id="reusing-existing-subnet-ranges_{context}"]

= Reusing existing subnet ranges

You can reuse existing subnet ranges if they have enough IP addresses to allocate to the new control plane services. You configure the new control plane services to use the same subnet as you used in the adopted environment, and configure the allocation pools that are used by the new services to exclude IP addresses that are already allocated to existing cluster nodes. By reusing existing subnets, you avoid additional routing configuration between the old and new subnets. as in xref:using-new-subnet-ranges_{context}[Configuring new subnet ranges].

If your existing subnets do not have enough IP addresses in the existing subnet ranges for the new control plane services, you must create new subnet ranges. For more information, see xref:using-new-subnet-ranges_{context}[Using new subnet ranges].

No special routing configuration is required to reuse subnet ranges. However, you must ensure that already consumed IP addresses do not overlap with the new allocation pools configured for {rhos_long_noacro} control plane services.

If you are especially constrained by the size of the existing subnet, you may
have to apply elaborate exclusion rules when defining allocation pools for the
new control plane services. For more information, see

