[id="adopting-the-networking-service_{context}"]

= Adopting the {networking}

Adopting {networking_first_ref} means that an existing `OpenStackControlPlane` custom resource (CR), where the {networking}
is supposed to be disabled, should be patched to start the service with the
configuration parameters provided by the source environment.

When the procedure is over, the expectation is to see the `NeutronAPI` service is running: the {identity_service_first_ref} endpoints should be updated and the same backend of the source Cloud will be available. If the conditions above are met, the adoption is considered concluded.

This guide also assumes that:

. A `TripleO` environment (the source Cloud) is running on one side;
. A `SNO` / `CodeReadyContainers` is running on the other side.

.Prerequisites

* Previous Adoption steps completed. Notably, MariaDB and Keystone and xref:migrating-ovn-data_migrating-databases[Migrating OVN data]
should be already adopted.

.Procedure
//The following link takes me to a 404. Do we need this text? I think we should start the procedure at "Patch OpenStackControlPlane..."
As already done for https://github.com/openstack-k8s-operators/data-plane-adoption/blob/main/keystone_adoption.md[Keystone], the Neutron Adoption follows the same pattern.

* Patch `OpenStackControlPlane` to deploy {networking}:
+
----
oc patch openstackcontrolplane openstack --type=merge --patch '
spec:
  neutron:
    enabled: true
    apiOverride:
      route: {}
    template:
      override:
        service:
          internal:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/allow-shared-ip: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.80
            spec:
              type: LoadBalancer
      databaseInstance: openstack
      databaseAccount: neutron
      secret: osp-secret
      networkAttachments:
      - internalapi
'
----

.Verification

* Inspect the resulting {networking} pods:
+
----
NEUTRON_API_POD=`oc get pods -l service=neutron | tail -n 1 | cut -f 1 -d' '`
oc exec -t $NEUTRON_API_POD -c neutron-api -- cat /etc/neutron/neutron.conf
----

* Check that the `Neutron API` service is registered in the {identity_service}: 
+
----
$ openstack service list | grep network
----
+
----
$ openstack endpoint list | grep network

| 6a805bd6c9f54658ad2f24e5a0ae0ab6 | regionOne | neutron      | network      | True    | public    | http://neutron-public-openstack.apps-crc.testing  |
| b943243e596847a9a317c8ce1800fa98 | regionOne | neutron      | network      | True    | internal  | http://neutron-internal.openstack.svc:9696        |
| f97f2b8f7559476bb7a5eafe3d33cee7 | regionOne | neutron      | network      | True    | admin     | http://192.168.122.99:9696                        |
----

* Create sample resources. You can test whether the user can create networks, subnets, ports, or routers.
+
----
$ openstack network create net
$ openstack subnet create --network net --subnet-range 10.0.0.0/24 subnet
$ openstack router create router
----

//NOTE: this page should be expanded to include information on SR-IOV adoption.
