:_mod-docs-content-type: ASSEMBLY
ifdef::context[:parent-context: {context}]

[id="adopting-data-plane_{context}"]

:context: data-plane

= Adopting the data plane

[role="_abstract"]
Adopting the {rhos_long} data plane involves the following steps:

ifeval::["{build_variant}" != "ospdo"]
. Stop any remaining services on the {rhos_prev_long} ({OpenStackShort}) {rhos_prev_ver} control plane.
endif::[]
. Deploy the required custom resources.
. Perform a fast-forward upgrade on Compute services from {OpenStackShort} {rhos_prev_ver} to {rhos_acro} {rhos_curr_ver}.
. Adopt Networker services to the {rhos_acro} data plane.

[WARNING]
After the {rhos_acro} control plane manages the newly deployed data plane, you must not re-enable services on the {OpenStackShort} {rhos_prev_ver} control plane and data plane. If you re-enable services, workloads are managed by two control planes or two data planes, resulting in data corruption, loss of control of existing workloads, inability to start new workloads, or other issues.

include::../modules/proc_stopping-infrastructure-management-and-compute-services.adoc[leveloffset=+1]

include::../modules/proc_adopting-compute-services-to-the-data-plane.adoc[leveloffset=+1]

include::../modules/proc_adopting-compute-services-with-dcn-backend.adoc[leveloffset=+1]

include::../modules/proc_performing-a-fast-forward-upgrade-on-compute-services.adoc[leveloffset=+1]

include::../modules/proc_adopting-networker-services-to-the-data-plane.adoc[leveloffset=+1]

include::../modules/proc_enabling-high-availability-for-instances.adoc[leveloffset=+1]

include::../modules/proc_performing-post-adoption-cleanup-of-load-balancers.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
