ifdef::context[:parent-context: {context}]

[id="migrating-ceph-rgw_{context}"]

:context: migrating-ceph-rgw

= Migrating {Ceph} RGW to external RHEL nodes

For hyperconverged infrastructure (HCI) or dedicated Storage nodes that are running {Ceph} version 6 or later, you must migrate the RGW daemons that are included in the {rhos_prev_long} Controller nodes into the existing external Red Hat Enterprise Linux (RHEL) nodes. The existing external RHEL nodes typically include the Compute nodes for an HCI environment or {Ceph} nodes.

To migrate Ceph Object Gateway (RGW), your environment must meet the following requirements:

* {Ceph} is running version 6 or later and is managed by cephadm/orchestrator.
* An undercloud is still available, and the nodes and networks are managed by {OpenStackPreviousInstaller}.

include::../modules/proc_completing-prerequisites-for-migrating-ceph-rgw.adoc[leveloffset=+1]

include::../modules/proc_migrating-the-rgw-backends.adoc[leveloffset=+1]

include::../modules/proc_deploying-a-ceph-ingress-daemon.adoc[leveloffset=+1]

include::../modules/proc_updating-the-object-storage-endpoints.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
