ifdef::context[:parent-context: {context}]

[id="migrating-ceph-monitoring_{context}"]

:context: migrating-ceph-monitoring

= Migrating the monitoring stack component to new nodes within an existing {Ceph} cluster

The Ceph Dashboard module adds web-based monitoring and administration to the
Ceph Manager.
With {OpenStackPreviousInstaller}-deployed {Ceph}, this component is enabled as
part of the overcloud deploy and it is composed of the following:

- Ceph Manager module
- Grafana
- Prometheus
- Alertmanager
- Node exporter

The Ceph Dashboard containers are included through
`tripleo-container-image-prepare` parameters and the high availability relies
on `Haproxy` and `Pacemaker` deployed on the {OpenStackShort} front. For an
external {CephCluster} cluster, high availability is not supported. The goal of
this procedure is to migrate and relocate the Ceph Monitoring components to
free Controller nodes.

For this procedure, we assume that we are beginning with a {OpenStackShort}
based on {rhos_prev_ver} and a {Ceph} {CephVernum} deployment managed by
{OpenStackPreviousInstaller}. We assume that:

* {Ceph} has been upgraded to {CephVernum} and is managed by
  cephadm/orchestrator
* Both the {Ceph} public and cluster networks are propagated,
  through {OpenStackPreviousInstaller}, to the target nodes

include::../modules/proc_completing-prerequisites-for-migrating-ceph-monitoring-stack.adoc[leveloffset=+1]

include::../assemblies/assembly_migrating-monitoring-stack-to-target-nodes.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
