ifdef::context[:parent-context: {context}]

[id="configuring-isolated-networks_{context}"]

:context: isolated-networks

= Configuring isolated networks

Before you begin replicating your existing VLAN and IPAM configuration in the {rhos_long} environment, you must have the following IP address allocations for the new control plane services:

* 1 IP address, per isolated network, per {rhocp_long} worker node. These IP addresses configure {OpenShiftShort} worker nodes to the `NodeNetworkConfigurationPolicy` custom resources (CRs). For more information, see xref:configuring-openshift-worker-nodes_isolated-networks[Configuring {OpenShiftShort} worker nodes].
* 1 IP range, per isolated network, for the data plane nodes. These ranges
configure data plane nodes to `NetConfig` CRs. For more information, see xref:configuring-data-plane-nodes_isolated-networks[Configuring data plane nodes].
* 1 IP range, per isolated network, for control plane services. These ranges
enable pod connectivity to isolated networks to
`NetworkAttachmentDefinition` CRs. For more information, see xref:configuring-networking-for-control-plane-services_isolated-networks[Configuring the networking for control plane services].
* 1 IP range, per isolated network, for load balancer IP addresses. These IP ranges define load balancer IP addresses for MetalLB in the `IPAddressPool` CRs. For more information, see xref:configuring-networking-for-control-plane-services_isolated-networks[Configuring the networking for control plane services].

[NOTE]
The exact list and configuration of isolated networks in this procedure should reflect the actual adopted environment. The number of isolated networks might differ from the examples used in this procedure. IPAM scheme might also differ.
Only relevant parts of the configuration are shown. Examples are incomplete and
should be incorporated into the general configuration for the new deployment,
as described in the general {rhos_prev_long} documentation.

include::../modules/proc_configuring-openshift-worker-nodes.adoc[leveloffset=+1]

include::../modules/proc_configuring-networking-for-control-plane-services.adoc[leveloffset=+1]

include::../modules/proc_configuring-data-plane-nodes.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
