ifdef::context[:parent-context: {context}]

[id="adopting-the-shared-file-systems-service_{context}"]

:context: adopting-shared-file-systems

= Adopting the {rhos_component_storage_file}

The {rhos_component_storage_file_first_ref} in {rhos_long} provides a self-service API to create and manage file shares. File shares (or "shares"), are built for concurrent read/write access from multiple clients. This makes the {rhos_component_storage_file} essential in cloud environments that require a ReadWriteMany persistent storage.

File shares in {rhos_acro} require network access. Ensure that the networking in the {rhos_prev_long} ({OpenStackShort}) {rhos_prev_ver} environment matches the network plans for your new cloud after adoption. This ensures that tenant workloads remain connected to storage during the adoption process. The {rhos_component_storage_file} control plane services are not in the data path. Shutting down the API, scheduler, and share manager services do not impact access to existing shared file systems.

Typically, storage and storage device management are separate networks. Shared File Systems services only need access to the storage device management network.
For example, if you used a {CephCluster} cluster in the deployment, the "storage"
network refers to the {CephCluster} cluster's public network, and the Shared File Systems service's share manager service needs to be able to reach it.

The {rhos_component_storage_file} supports the following storage networking scenarios:

* You can directly control the networking for your respective file shares.
* The {rhos_acro} administrator configures the storage networking.


include::../modules/con_preparing-the-shared-file-systems-service-configuration.adoc[leveloffset=+1]

include::../modules/proc_deploying-file-systems-service-control-plane.adoc[leveloffset=+1]

include::../modules/proc_decommissioning-rhosp-standalone-ceph-NFS-service.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
