ifdef::context[:parent-context: {context}]

[id="migrating-monitoring-stack-to-target-nodes_{context}"]

:context: migrating-monitoring-stack

= Migrating the monitoring stack to the target nodes

To migrate the monitoring stack to the target nodes, you add the monitoring label to your existing nodes and update the configuration of each daemon. You do not need to migrate node exporters. These daemons are deployed across
the nodes that are part of the {Ceph} cluster (the placement is ‘*’).

.Prerequisites
* Confirm that the firewall rules are in place and the ports are open for a given monitoring stack service.

[NOTE]
Depending on the target nodes and the number of deployed or active daemons, you can either relocate the existing containers to the target nodes, or
select a subset of nodes that host the monitoring stack daemons. High availability (HA) is not supported. Reducing the placement with `count: 1`  allows you to migrate the existing daemons in a Hyperconverged Infrastructure, or hardware-limited, scenario without impacting other services.

include::../modules/proc_migrating-existing-daemons-to-target-nodes.adoc[leveloffset=+1]

ifeval::["{build}" != "downstream"]
include::../modules/proc_relocating-one-instance-of-a-monitoring-stack-to-migrate-daemons-to-target-nodes.adoc[leveloffset=+1]
endif::[]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
