ifdef::context[:parent-context: {context}]

[id="configuring-network-for-RHOSO-deployment_{context}"]

:context: configuring-network

= Configuring the network for the RHOSO deployment

With {rhocp_long}, the network is a very important aspect of the deployment, and
it is important to plan it carefully. The general network requirements for the
{rhos_prev_long} ({OpenStackShort}) services are not much different from the ones in a {OpenStackPreviousInstaller} deployment, but the way you handle them is.

[NOTE]
For more information about the network architecture and configuration, see
link:{deploying-rhoso}/assembly_preparing-rhocp-for-rhoso[Preparing Red Hat OpenShift Container Platform for {rhos_long_noacro}] in the _ {deploying-rhoso-t}_guide and link:{defaultOCPURL}/networking/about-networking.html[About networking].

When adopting a new {OpenStackShort} deployment, it is important to align the network
configuration with the adopted cluster to maintain connectivity for existing
workloads.

The following logical configuration steps will incorporate the existing network
configuration:

* configure **{OpenShiftShort} worker nodes** to align VLAN tags and IPAM
  configuration with the existing deployment.
* configure **Control Plane services** to use compatible IP ranges for
  service and load balancing IPs.
* configure **Data Plane nodes** to use corresponding compatible configuration for
  VLAN tags and IPAM.

Specifically,

* IPAM configuration will either be reused from the
  **existing** deployment or, depending on IP address availability in the
  existing allocation pools, **new** ranges will be defined to be used for the
  new control plane services. If so, **IP routing** will be configured between
  the old and new ranges. For more information, see xref:planning-your-ipam-configuration_configuring-network[Planning your IPAM configuration].
* VLAN tags will be reused from the existing deployment.

include::../modules/proc_retrieving-network-information-from-your-existing-deployment.adoc[leveloffset=+1]

include::../assemblies/assembly_planning-your-ipam-configuration.adoc[leveloffset=+1]

include::../assemblies/assembly_configuring-isolated-networks.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
