ifdef::context[:parent-context: {context}]

[id="configuring-network-for-RHOSO-deployment_{context}"]

:context: configuring-network

= Configuring the network for the RHOSO deployment

With {rhocp_long}, the network is a very important aspect of the deployment, and
it is important to plan it carefully. The general network requirements for the
{rhos_prev_long} ({OpenStackShort}) services are not much different from the ones in a {OpenStackPreviousInstaller} deployment, but the way you handle them is.

[NOTE]
For more information about the network architecture and configuration, see
link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/18.0-dev-preview/html/deploying_red_hat_openstack_platform_18.0_development_preview_3_on_red_hat_openshift_container_platform/assembly_preparing-rhocp-for-rhosp[_Deploying Red Hat OpenStack Platform 18.0 Development Preview 3 on Red Hat OpenShift Container Platform_] and link:https://docs.openshift.com/container-platform/4.15/networking/about-networking.html[About
networking] in _OpenShift Container Platform 4.15 Documentation_. This document will address concerns specific to adoption.

// TODO: update the openstack link with the final documentation

// TODO: should we parametrize the version in the links somehow?

When adopting a new {OpenStackShort} deployment, it is important to align the network
configuration with the adopted cluster to maintain connectivity for existing
workloads.

The following logical configuration steps will incorporate the existing network
configuration:

* configure **{OpenShiftShort} worker nodes** to align VLAN tags and IPAM
  configuration with the existing deployment.
* configure **Control Plane services** to use compatible IP ranges for
  service and load balancing IPs.
* configure **Data Plane nodes** to use corresponding compatible configuration for
  VLAN tags and IPAM.

Specifically,

* IPAM configuration will either be reused from the
  **existing** deployment or, depending on IP address availability in the
  existing allocation pools, **new** ranges will be defined to be used for the
  new control plane services. If so, **IP routing** will be configured between
  the old and new ranges. For more information, see xref:planning-your-ipam-configuration_configuring-network[Planning your IPAM configuration].
* VLAN tags will be reused from the existing deployment.

include::../modules/proc_retrieving-network-information-from-your-existing-deployment.adoc[leveloffset=+1]

include::../assemblies/assembly_planning-your-ipam-configuration.adoc[leveloffset=+1]

include::../assemblies/assembly_configuring-isolated-networks.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
