ifdef::context[:parent-context: {context}]

[id="migrating-ceph-monitoring_{context}"]

:context: migrating-ceph-monitoring

= Migrating the monitoring stack component to new nodes within an existing {Ceph} cluster

The {Ceph} Dashboard module adds web-based monitoring and administration to the
Ceph Manager. With {OpenStackPreviousInstaller}-deployed {Ceph}, the {Ceph} Dashboard is enabled as part of the overcloud deploy and is composed of the following components:

* Ceph Manager module
* Grafana
* Prometheus
* Alertmanager
* Node exporter

The {Ceph} Dashboard containers are included through `tripleo-container-image-prepare` parameters, and high availability (HA) relies
on `HAProxy` and `Pacemaker` to be deployed on the {rhos_prev_long} ({OpenStackShort}) environment. For an external {CephCluster} cluster, HA is not supported.

In this procedure, you migrate and relocate the Ceph Monitoring components to free Controller nodes.

.Prerequisites

* Complete the tasks in your {rhos_prev_long} {rhos_prev_ver} environment. For more information, see xref:red-hat-ceph-storage-prerequisites_configuring-network[{Ceph} prerequisites].


include::../assemblies/assembly_migrating-monitoring-stack-to-target-nodes.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
