ifdef::context[:parent-context: {context}]

[id="configuring-isolated-networks_{context}"]

:context: isolated-networks

= Configuring isolated networks

At this point, you should have a good idea about VLAN and IPAM configuration
you would like to replicate in the new environment.

Before proceeding, you should have a list of the following IP address
allocations to be used for the new control plane services:

* 1 IP address, per isolated network, per {rhocp_long} worker node. (These
  addresses configure openshift worker nodes to
  `NodeNetworkConfigurationPolicy` custom resources (CRs).) For more information, see xref:configuring-openshift-worker-nodes_isolated-networks[Configuring {rhocp_long} worker nodes].
* IP range, per isolated network, for the data plane nodes. (These ranges will
  configure data plane nodes to `NetConfig` CRs.) For more information, see xref:configuring-data-plane-nodes_isolated-networks[Configuring data plane nodes].
* IP range, per isolated network, for control plane services. (These ranges
  will enable pod connectivity to isolated networks to
  `NetworkAttachmentDefinition` CRs.) For more information, see xref:configuring-networking-for-control-plane-services_isolated-networks[Configuring the networking for control plane services].
* IP range, per isolated network, for load balancer IP addresses. (These ranges will define load balancer IP addresses to `IPAddressPool` CRs for MetalLB.) For more information, see xref:configuring-networking-for-control-plane-services_isolated-networks[Configuring the networking for control plane services].

[IMPORTANT]
Make sure you have the information listed above before proceeding with the next steps.

[NOTE]
The exact list and configuration of isolated networks in the examples
listed below should reflect the actual adopted environment. The number of
isolated networks may differ from the example below. IPAM scheme may differ.
Only relevant parts of the configuration are shown. Examples are incomplete and
should be incorporated into the general configuration for the new deployment,
as described in the general {rhos_prev_long} documentation.

include::../modules/proc_configuring-openshift-worker-nodes.adoc[leveloffset=+1]

include::../modules/proc_configuring-networking-for-control-plane-services.adoc[leveloffset=+1]

include::../modules/proc_configuring-data-plane-nodes.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
