:_mod-docs-content-type: ASSEMBLY
ifdef::context[:parent-context: {context}]

[id="adopting-the-image-service_{context}"]

:context: image-service

= Adopting the {image_service}

[role="_abstract"]
To adopt the {image_service_first_ref} you patch an existing `OpenStackControlPlane` custom resource (CR) that has the {image_service} disabled. The patch starts the service with the configuration parameters that are provided by the {rhos_prev_long} ({OpenStackShort}) environment.

The {image_service} adoption is complete if you see the following results:

* The `GlanceAPI` service up and running.
* The {identity_service} endpoints are updated, and the same back end of the source cloud is available.

To complete the {image_service} adoption, ensure that your environment meets the following criteria:

* You have a running {OpenStackPreviousInstaller} environment (the source cloud).
* You have a Single Node OpenShift or OpenShift Local that is running in the {rhocp_long} cluster.
* Optional: You can reach an internal/external `Ceph` cluster by both `crc` and {OpenStackPreviousInstaller}.

If you have image quotas in {OpenStackShort} {rhos_prev_ver}, these quotas are transferred to {rhos_long} {rhos_curr_ver} because the image quota system in {rhos_curr_ver} is disabled by default. For more information about enabling image quotas in {rhos_curr_ver}, see link:{defaultURL}/customizing_persistent_storage/assembly_glance-customizing-the-image-service_customizing-cinder#assembly_glance-configuring-quotas_configuring-glance[Configuring image quotas] in _Customizing persistent storage_. If you enable image quotas in {rhos_acro} {rhos_curr_ver}, the new quotas replace the legacy quotas from {OpenStackShort} {rhos_prev_ver}.

include::../modules/proc_adopting-image-service-with-object-storage-backend.adoc[leveloffset=+1]

include::../modules/proc_adopting-image-service-with-block-storage-backend.adoc[leveloffset=+1]

include::../modules/proc_adopting-image-service-with-nfs-backend.adoc[leveloffset=+1]

include::../modules/proc_adopting-image-service-with-ceph-backend.adoc[leveloffset=+1]

include::../modules/proc_adopting-image-service-with-dcn-backend.adoc[leveloffset=+1]

include::../modules/proc_verifying-the-image-service-adoption.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
