ifdef::context[:parent-context: {context}]

[id="planning-your-ipam-configuration_{context}"]

:context: ipam-configuration

= Planning your IPAM configuration

The new deployment model puts additional burden on the size of IP allocation
pools available for {rhos_prev_long} ({OpenStackShort}) services. This is because each service deployed
on {rhocp_long} worker nodes will now require an IP address from the IPAM pool (in
the previous deployment model, all services hosted on a controller node shared
the same IP address.)

Since the new control plane deployment has different requirements as to the
number of IP addresses available for services, it may even be impossible to
reuse the existing IP ranges used in adopted environment, depending on its
size. Prudent planning is required to determine which options are available in
your particular case.

The total number of IP addresses required for the new control plane services,
in each isolated network, is calculated as a sum of the following:

* The number of {OpenShiftShort} worker nodes. (Each node will require 1 IP address in
  `NodeNetworkConfigurationPolicy` custom resources (CRs).)
* The number of IP addresses required for the data plane nodes. (Each node will require
  an IP address from `NetConfig` CRs.)
* The number of IP addresses required for control plane services. (Each service
  will require an IP address from `NetworkAttachmentDefinition` CRs.) This
  number depends on the number of replicas for each service.
* The number of IP addresses required for load balancer IP addresses. (Each
  service will require a VIP address from `IPAddressPool` CRs.)

As of the time of writing, the simplest single worker node {OpenShiftShort} deployment
(CRC) has the following IP ranges defined (for the `internalapi` network):

* 1 IP address for the single worker node;
* 1 IP address for the data plane node;
* `NetworkAttachmentDefinition` CRs for control plane services:
  `X.X.X.30-X.X.X.70` (41 addresses);
* `IPAllocationPool` CRs for load balancer IPs: `X.X.X.80-X.X.X.90` (11
  addresses).

Which comes to a total of 54 IP addresses allocated to the `internalapi`
allocation pools.

// TODO: update the numbers above for a more realistic multinode cluster.

The exact requirements may differ depending on the list of {OpenStackShort} services
to be deployed, their replica numbers, as well as the number of {OpenShiftShort}
worker nodes and data plane nodes.

Additional IP addresses may be required in future {OpenStackShort} releases, so it is
advised to plan for some extra capacity, for each of the allocation pools used
in the new environment.

Once you know the required IP pool size for the new deployment, you can choose
one of the following scenarios to handle IPAM allocation in the new
environment.

The first listed scenario is more general and implies using new IP ranges,
while the second scenario implies reusing the existing ranges. The end state of
the former scenario is using the new subnet ranges for control plane services,
but keeping the old ranges, with their node IP address allocations intact, for
data plane nodes.

Regardless of the IPAM scenario, the VLAN tags used in the existing deployment will be reused in the new deployment. Depending on the scenario, the IP address ranges to be used for control plane services will be either reused from the old deployment or defined anew. Adjust the configuration as described in xref:configuring-isolated-networks_configuring-network[Configuring isolated networks].

include::../modules/proc_using-new-subnet-ranges.adoc[leveloffset=+1]

include::../modules/proc_reusing-existing-subnet-ranges.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
