[id="adopting-the-image-service_{context}"]

:context: image-service

= Adopting the {image_service}

To adopt the {image_service_first_ref} you patch an existing `OpenStackControlPlane` custom resource (CR) that has the {image_service} disabled. The patch starts the service with the configuration parameters that are provided by the {rhos_prev_long} ({OpenStackShort}) environment.

The {image_service} adoption is complete if you see the following results:

* The `GlanceAPI` service up and running. 
* The {identity_service} endpoints are updated, and the same back end of the source cloud is available. 

.Prerequisites

* A {OpenStackPreviousInstaller} environment (the source cloud) is running.
* A Single Node OpenShift or OpenShift Local is running in the {OpenShift} cluster.
* Optional: You can reach an internal/external `Ceph` cluster is by both `crc` and {OpenStackPreviousInstaller}.

ifeval::["{build}" != "downstream"]
//This link goes to a 404.
As already done for https://github.com/openstack-k8s-operators/data-plane-adoption/blob/main/keystone_adoption.md[Keystone], the Glance Adoption follows the same pattern.
endif::[]

include::../modules/proc_adopting-image-service-with-object-storage-backend.adoc[leveloffset=+1]

include::../modules/proc_adopting-image-service-with-block-storage-backend.adoc[leveloffset=+1]

include::../modules/proc_adopting-image-service-with-nfs-ganesha-backend.adoc[leveloffset=+1]

include::../modules/proc_adopting-image-service-with-ceph-backend.adoc[leveloffset=+1]

include::../modules/proc_verifying-the-image-service-adoption.adoc[leveloffset=+1]
