name: Build Docs
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/docs*
      - docs_dev/**
      - Gemfile
      - Makefile
permissions:
  contents: read
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: '3.9'
      - uses: ruby/setup-ruby@003a5c4d8d6321bd302e38f6f0ec593f77f06600 # v1
        with:
          ruby-version: '3.2'

      - name: Install Asciidoc
        run: make docs-dependencies

      - name: Build dev docs
        run: make docs-dev

      - name: Prepare site
        run: |
          mkdir -p _site
          mv -T docs_build/adoption-dev _site/dev

          mv _site/dev/index-upstream.html _site/dev/index.html

          cat > _site/index.html <<EOF
          <!DOCTYPE html>
          <html>
          <head>
              <meta name="viewport" content="width=device-width, initial-scale=1.0" />
              <style>
                  body {
                      margin: 0;
                      font-family: Arial, Helvetica, sans-serif;
                  }

                  .asciidoc {
                      height:90vh;
                      background:#fff;
                      color:#fff;
                  }

                  .topnav {
                      overflow: hidden;
                      background-color: #333;
                  }

                  .topnav a {
                      float: left;
                      color: #f2f2f2;
                      text-align: center;
                      padding: 2vh 2vh;
                      text-decoration: none;
                      font-size: 2vh;
                  }

                  .topnav a:hover {
                      background-color: #ddd;
                      color: black;
                  }

                  .topnav a.active {
                      background-color: #7a2518;
                      color: white;
                  }
              </style>
          </head>

          <body>

              <div class="topnav">
                  <a href="dev/" target="content">Contributor</a>
              </div>

              <div class="asciidoc">
                  <iframe name="content" width="100%" height="100%" src="dev/index.html"></iframe>
              </div>

          </body>
          </html>
          EOF

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
        with:
          path: _site

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5
